### ISSUE TITLE
Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0)

### ISSUE THREAD

**Issue by mdudis** [Azure/azure-functions-python-worker#357] opened 2019-03-05 19:29 UTC
I developed a function which inserts data to Azure SQL Server when an excel file is uploaded to Azure storage container. Function works perfectly fine on local machine. After testing locally I deployed the function using below command:-

func azure functionapp publish 'functionname' --build-native-deps --additional-packages "python3-dev libevent-dev unixodbc-dev" --force --no-bundler

On Uploading file to storage account after deployment to Azure, I see below error in logs:-

Result: Failure
Exception: Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")
Stack:   File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 288, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 347, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/ProcessExcelApp1EU0304/__init__.py", line 44, in main
    cnxn=pyodbc.connect(dbconnection)

Please provide the following:

- Timestamp:2019-03-05 19:05:57.735
- Function App name:ProcessExcelApp1EU0304
- Function name(s) (as appropriate):ProcessExcelApp1EU0304
- Core Tools version: Azure Functions Core Tools (2.4.317 Commit hash:63e1996b6c281079427e7c9b8a0a1c633988a195)
Function Runtime Version: 2.0.12285.0

#### Repro steps

Provide the steps required to reproduce the problem:

1. Upload a file to storage account container configured to trigger the function from
2. Data should get inserted to Azure SQL Server DB  url for which is setup in application settings

#### Expected behavior

Function should read the excel file and then data should get inserted to Azure SQL Server DB  url for which is setup in application settings

#### Actual behavior

Result: Failure
Exception: Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")
Stack:   File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 288, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 347, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/ProcessExcelApp1EU0304/__init__.py", line 44, in main
    cnxn=pyodbc.connect(dbconnection)

#### Known workarounds

Have to run it locally for testing

#### Related information 

Provide any related information 

* Links to source
* Contents of the requirements.txt file
* Bindings used

<!-- Uncomment this if you want to include your source (wrap it in details to make browsing easier)
<details>
<summary>Source</summary>

```python
# __init__.py

import logging
import pandas as pd
import json
import azure.functions as func
from urllib.request import urlopen
import pyodbc
import os
import uuid
def main(myblob: func.InputStream):
    logging.info(f"Python blob trigger function processed blob \n"
                 f"Name: {myblob.name}\n"
                 f"Blob Size: {myblob.length} bytes")
    filename=myblob.name
    file1=myblob.uri
    socket=urlopen(file1)
    xl = pd.ExcelFile(socket)
    df1 = xl.parse('Sheet1')
    dbconnection=os.environ.get('SQLSERVER')
    logging.info(dbconnection)
    cnxn=pyodbc.connect(dbconnection)
    cursor = cnxn.cursor()
    values_list=[]
    for i in df1.index:
        values=()
        values=(filename,df1['Lot Type Id'][i],df1['Lot Id'][i],df1['Varietal'][i],str(df1['FacilityId'][i]),df1['BuyerId'][i],
                df1['SellerId'][i],int(df1['Volume'][i]),df1['UOM'][i],int(df1['Price'][i]),df1['Currency'][i],df1['Terms'][i],
                str(df1['Delivery Date'][i]),
                df1['Physical Product State'][i],df1['PO Release Number'][i],'new')
        values_list.append(values)
        stmt="""INSERT INTO --table name (FileName,LotTypeId,LotId,Varietal,FacilityId,Buyer,Seller,Volume,UnitOfMeasure,Price,Currency,Terms,DeliveryDate,PhysicalProductState,POReleaseNumber,FDLCreationStatus) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""
        try:
            result=cursor.execute(stmt,values)
        except Exception as e: 
            print(e)
            print('failed for id'+str(df1['Lot Id'][i]))
    cursor.commit()
    cursor.close()
    logging.info('Inserted rows to DB')
```

requirement.txt details:-

azure-functions==1.0.0b3
azure-functions-worker==1.0.0b3
grpcio==1.14.2
grpcio-tools==1.14.2
numpy==1.16.2
pandas==0.24.1
protobuf==3.7.0
pyodbc==4.0.26
python-dateutil==2.8.0
pytz==2018.9
six==1.12.0
xlrd==1.2.0

**Comment by vikasapr** [comment] 2019-03-08 00:38
I assume you also use os-type Linux. Did you test the function locally on Windows or Linux. But regardless one thing is that pyodbc may not install seamlessly (i.e. just with pip) on Linux VM where Azure function will run and hence the issue. I am also interested in a solution to this problem.

**Comment by mdudis** [comment] 2019-03-08 00:46
I am using Windows 10 machine to develop locally and deployed after testing locally. 

Found a work around today afternoon. If I replace {ODBC Driver 13 for SQL Server} to {ODBC Driver 17 for SQL Server} in connection string then it is working fine. But I am not really sure if this is the right way to do it because Azure SQL DB connection string has {ODBC Driver 13 for SQL Server} in connection string.

**Comment by vikasapr** [comment] 2019-03-08 00:50
Wow. Great. Thanks for sharing. I do not see any problem if that can work. Related question. How do you store connection string / DB password? Is it in Python code itself? If not in the code or securely, would you mind sharing how?

**Comment by mdudis** [comment] 2019-03-08 00:55
I am storing connection string in application settings but would be exploring if azure-key-vault can be used as well.

**Comment by vikasapr** [comment] 2019-03-08 00:57
Thanks. I tried that way. os.environ['<App setting>'] gives me key error in my code. How do I access it?

**Comment by mdudis** [comment] 2019-03-08 01:00
first you need to fetch application settings in your local environment..
func azure functionapp fetch-app-settings xxxxxxx(your func name)

then you can access it as below:-

con=os.environ.get('CONSTRING')

**Comment by vikasapr** [comment] 2019-03-08 01:03
Cool. thanks. I will give it a try.

**Comment by vikasapr** [comment] 2019-04-24 05:55
Today April 23, 2019, I tried to spin up a new Azure function 2.0 on OS-type Linux and runtime Python 3.6
When I add **pyodbc** in requirements file, I am unable to publish the app (without it, the app publishes)
**I am using --build-native-deps
and running docker locally on my Windows 10 box.**

This is the error I get, 
`Building wheels for collected packages: pyodbc, pycparser
  Building wheel for pyodbc (setup.py) ... error
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0g7v0744/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-cw8pu7rd --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'pyodbc' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPYODBC_VERSION=4.0.23 -I/usr/local/include/python3.6m -c src/textenc.cpp -o build/temp.linux-x86_64-3.6/src/textenc.o -Wno-write-strings
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
`

Any help? Something changed or I am missing something

**Comment by vikasapr** [comment] 2019-04-24 18:35
This happened because docker image was missing gcc. Adding these options --additional-packages "build-essential libevent-dev unixodbc-dev" fixed it.

**Comment by LukeGahan** [comment] 2019-04-25 09:45
Thanks @vikasapr worked for me. Is that image missing gcc by design?

**Comment by ankitkumarr** [comment] 2019-05-01 18:58
This is fixed in the latest release (`2.6.1048` <=) of `azure-functions-core-tools` . https://github.com/Azure/azure-functions-core-tools/issues/1211 for more information.

**Closed** 2019-07-02 23:01 UTC
Labels: func-stack: Python

**Comment by mathshenry** [comment] 2019-07-12 22:25
Hi all!
I'm facing the same problem: Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0)
But I have already changed the settings to: 'driver' : 'ODBC Driver 13 for SQL Server'
Does anyone know how I could get it working?

Thanks in advance!

**Comment by maiqbal11** [comment] 2019-07-12 22:37
@mathshenry, could try  'ODBC Driver **17** for SQL Server'? That is the version we have installed in the image.

**Comment by mathshenry** [comment] 2019-07-15 17:08
@maiqbal11 Sorry, I misspelled there. I did change it to 17 but it still complains that the 13 is not found. I don't know what to do so that it could recognize that I changed the version.

**Comment by mathshenry** [comment] 2019-07-15 19:24
Hey guys! I just found what the problem was. The project was configured using "options" (in lower case) so Django was always using the default (13). Now I set it to Uppercase ("OPTIONS") and it is getting the 17 correctly.

Thanks, @maiqbal11 !

**Comment by tanzeel-bhatti** [comment] 2019-09-29 19:41
> Hey guys! I just found what the problem was. The project was configured using "options" (in lower case) so Django was always using the default (13). Now I set it to Uppercase ("OPTIONS") and it is getting the 17 correctly.
> 
> Thanks, @maiqbal11 !

Can you please share your config. I want to know how were you able to connect to MSSQL from your Django project. I am still facing problems

**Comment by mathshenry** [comment] 2019-11-25 17:29
> > Hey guys! I just found what the problem was. The project was configured using "options" (in lower case) so Django was always using the default (13). Now I set it to Uppercase ("OPTIONS") and it is getting the 17 correctly.
> > Thanks, @maiqbal11 !
> 
> Can you please share your config. I want to know how were you able to connect to MSSQL from your Django project. I am still facing problems

Sorry mate, haven't been using GitHub in a while!
I can't show you the code because it's private and belongs to my enterprise. I'm sorry!
It's been a while, I hope you could resolve it!

**Comment by pawarv** [comment] 2020-04-16 08:23
> I am using Windows 10 machine to develop locally and deployed after testing locally.
> 
> Found a work around today afternoon. If I replace {ODBC Driver 13 for SQL Server} to {ODBC Driver 17 for SQL Server} in connection string then it is working fine. But I am not really sure if this is the right way to do it because Azure SQL DB connection string has {ODBC Driver 13 for SQL Server} in connection string.

Changing to ODBC Driver 17 for SQL Server from ODBC Driver 13 is not working for me. Is there any other change you have made? Does you function work on docker?

**Comment by akashmauryagithub** [comment] 2022-01-14 09:34
Even I am facing the same issue " '01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)") " even when I am passing ODBC 17>
Please help
