### ISSUE TITLE
devops-pipeline does not recognize devops organization 

### ISSUE THREAD

**Issue by JK87iab** [Azure/azure-functions-python-worker#449] opened 2019-06-03 20:15 UTC
Trying to use devops for building and publishing azure functions from visual studio code.

I used this [article ](https://docs.microsoft.com/en-us/azure/devops/java/vscode-extension?view=azure-devops) to connect to devops.

After running  `az functionapp devops-pipeline create` it wont find any organizations.

`Error finding organization. Please check that the organization exists by logging onto your dev.azure.com acocunt`

Loing via `dev.azure.com` works as expected. I am also project admin.

#### Investigative information

Please provide the following:

- Timestamp:[6/3/2019 8:11:15 PM]
- Function App name:
- Function name(s) (as appropriate):
- Core Tools version: 2.7.1158

`az functionapp devops-pipeline create --organization-name NAME --project-name NAME
`

**Comment by maiqbal11** [comment] 2019-06-03 20:28
@Hazhzeng, do you have insight into why this might be happening?

**Comment by Hazhzeng** [comment] 2019-06-03 20:58
Hi @JK87iab, instead of using `az functionapp devops-pipeline create --organization-name NAME --project-name NAME`

Could you try using `az functionapp devops-pipeline create` in your functionapp directory? It should guide you interactively to build a devops pipeline.

If it still doesn't work, please let me know.

**Comment by JK87iab** [comment] 2019-06-04 01:21
@Hazhzeng 

Getting 

```
Would you like to use an existing Azure Devops organization?  (y/n): y
There are no existing organizations, you need to create a new organization.
Please select a region for the new organization:
```

**Comment by Hazhzeng** [comment] 2019-06-04 19:56
@JK87iab Thanks for raising this issue. I will investigate and work on the fix in https://github.com/Azure/azure-functions-devops-build/issues/42.

**Comment by asavaritayal** [comment] 2019-06-10 20:33
Closing as a dupe of https://github.com/Azure/azure-functions-devops-build/issues/42

**Closed by asavaritayal** 2019-06-10 20:33 UTC

**Comment by freedev** [comment] 2020-11-20 17:46
I'm experiencing the same issue, it seems not resolved.
