### ISSUE TITLE
File Mounting in Linux

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-python-worker#376] opened 2019-04-03 19:02 UTC
Placeholder issue for enabling file mounting in Linux containers. Users may have very large files/number of files that they want to be able to access in their function application. Currently, they would need to package these with their function code and downloading would add to cold start each time the function is run. The users might instead want to upload these files once at the start and then access them from the mounted location (e.g. Azure Files). This gives the user control over whether they'd like to optimize for cold start vs. throughput (since these file accesses would likely happen over the network).

**Comment by asavaritayal** [comment] 2019-05-01 17:36
Closing as a duplicate of https://github.com/Azure/Azure-Functions/issues/1078

**Closed by asavaritayal** 2019-05-01 17:36 UTC
Labels: needs-investigation
