### ISSUE TITLE
Get target route parameters when using proxies

### ISSUE THREAD

**Issue by eduardomourar** [Azure/azure-functions-python-worker#342] opened 2019-02-21 11:42 UTC
#### Investigative information

Please provide the following:

- Function App version: 2.0.12285
- Python worker version: 1.0.0b3
- Function name: test-list

#### Repro steps

1. Create sample function based on source code below
2. Hit API `/api/list_proxy/group_1/product_a?validate=true`
2. It should be routed to `/api/list/`

#### Expected behavior

I expected to have route parameter from the target function and some additional information from source proxy in another property:

```json
{
  "route_params": {
    "group": "group_1",
    "product": "product_a"
  },
  "params": {
    "validate": "true"
  }
}
```

#### Actual behavior

Instead I have the route params from the original proxy:

```json
{
  "method": "POST",
  "url": "http://localhost:7071/api/list/group_1/product_a?validate=true",
  "headers": {
    "connection": "keep-alive"
  },
  "route_params": {
    "restOfPath": "group_1/product_a"
  },
  "params": {
    "validate": "true"
  },
  "get_body": ""
}
```

#### Known workarounds

We will add logic to our Function App to reconstruct the route params by using the URL and route from function.json. 

#### Related information 

Provide any related information 

* Sample source files
<details>
<summary>Source</summary>

```json
## function.json
{
  "scriptFile": "__init_py",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "request",
      "methods": [
        "post"
      ],
      "route": "list/{group}/{product}"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

```json
## proxies.json
{
  "proxies": {
    "internal-routing": {
      "matchCondition": {
        "route": "/api/list_proxy/{*restOfPath}"
       },
       "backendUri": "https://localhost/api/list/{restOfPath}"
      },
  }
}
```

```python
## __init_py
def main(request: azure.functions.HttpRequest) -> azure.functions.HttpResponse:

    route_params = {}
    if hasattr(request, 'route_params'):
        route_params = dict(request.route_params)
    params = {}
    if hasattr(request, 'params'):
        params = dict(request.params)
    headers = dict(request.headers)
    return json.dumps({
        'method': request.method,
        'url': request.url,
        'headers': headers,
        'route_params': route_params,
        'params': params,
        'get_body': request.get_body().decode(),
    })
```
</details>

**Comment by asavaritayal** [comment] 2019-02-26 17:48
@alexkarcher-msft can you take a look at this?

**Comment by alexkarcher-msft** [comment] 2019-02-26 18:06
This is fascinating. I know that Proxies calling a local function take a different code path compared to remote Proxies. 

When you call the python Function directly do the correct values get placed in the "route_params" variable? Also, if you put the same proxy in a different Function App, does that work as expected?

**Comment by eduardomourar** [comment] 2019-02-26 21:51
> When you call the python Function directly do the correct values get placed in the "route_params" variable?

Yes, I get the proper `route_params`.

> Also, if you put the same proxy in a different Function App, does that work as expected?

I will check this, but I assume that if I run with another python Function App I will get the same result.

**Comment by eduardomourar** [comment] 2019-02-27 02:38
Tested with the following setup:

1. Azure Functions Core Tools
  - Functions Core Tools (2.4.299 Commit hash: 0f105e9bc6e2faed71e8521d7541a909a6dcc389)
  - Function Runtime Version: 2.0.12285.0
  - Python worker version: 1.0.0b4
  - Result: `route_params` is wrong just as mentioned before in any Function App.

2. Python Docker Image
  - Function Runtime Version: 2.0.12309.0
  - Python worker version: 1.0.0b4
  - Result: `route_params` is as expected now.

My only suggestion then is to have the proxy details as part of Request object. I will have to wait until we have a v2.0.12309.0 python alpine image available to upgrade my environment.

**Comment by alexkarcher-msft** [comment] 2019-02-27 17:32
Cool! 
I was able to repo this issue on my own with a JS function, and setting the app setting [AZURE_FUNCTION_PROXY_DISABLE_LOCAL_CALL](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurefunctionproxydisablelocalcall) to true restored the correct behavior.

We're going to take a look at the root cause for this, but that app setting should mitigate the issue for the time being 🙂

**Comment by jeffhollan** [comment] 2019-02-27 17:44
Thanks @alexkarcher-msft and @eduardomourar for investigation.  Closing this one and will track work item here:
https://github.com/Azure/azure-functions-host/issues/3593

**Closed by jeffhollan** 2019-02-27 17:44 UTC
