### ISSUE TITLE
How to set CORS for python Functions

### ISSUE THREAD

**Issue by jashan05** [Azure/azure-functions-python-worker#451] opened 2019-06-05 10:23 UTC
#### Investigative information

Please provide the following:

- Timestamp:
- Function App name:**voting-app**
- Function name(s) (as appropriate):**cast_votes**
- Core Tools version: "2.0"

#### Repro steps

Provide the steps required to reproduce the problem:

How can i set the headers to allow access from anywhere

**Comment by asavaritayal** [comment] 2019-06-10 20:31
Closing as a dupe of https://github.com/Azure/azure-functions-python-worker/issues/444

**Closed by asavaritayal** 2019-06-10 20:31 UTC
