### ISSUE TITLE
Python function returns error 500 with empty body response

### ISSUE THREAD

**Issue by logachev** [Azure/azure-functions-python-worker#210] opened 2018-09-27 02:31 UTC
If I create a regular HttpTriggered Python function, it behaves differently if the body response is present or absent.

This works via test in the portal or locally, but returns error 500 via postman
```
return func.HttpResponse(status_code=200)
```

This works as expected:
```
return func.HttpResponse(“any-test”, status_code=200)
````

**Comment by elprans** [comment] 2018-09-27 21:31
I cannot reproduce on a simple test (624aeb2e9).  @logachev please post your `function.json`, function source and any available logs.

**Comment by elprans** [comment] 2018-09-27 21:31
Please also post the source of the request you are making.

**Comment by elprans** [comment] 2018-09-27 23:59
If it doesn't reproduce locally, it's unlikely to be a worker issue.  Do you have access to the logs?  @pragnagopa can you assist debugging this please?

**Comment by logachev** [comment] 2018-09-28 05:19
This is what I see in Worker logs (via kudu), it has a lot of records similar to this one with no details:
I don't see anything in Host or Function logs.

```
2018-09-26T20:37:14.348 [Information] bash process with Id=128 started
2018-09-26T20:37:17.586 [Error] Language Worker Process exited.
2018-09-26T20:37:15.211 [Information] Starting language worker process:bash  "/azure-functions-host/workers/python/start.sh" --host 127.0.0.1 --port 44827 --workerId c8c8b70c-ea9a-4d01-8567-6eed0bd04244 --requestId 44574384-67a5-4fed-958e-ba609c63392f --grpcMaxMessageLength 134217728
```

**Comment by pragnagopa** [comment] 2018-10-01 14:15
@maiqbal11 - Please update the issue when you have more info.

**Comment by tjhgit** [comment] 2018-10-25 20:13
I also deployed a python consumption app and noticed that the first http request after some idle time returns a 500. Repeating the request immediately again then leads to success. 
Does the underlying server take so long to start? I am currently using WestEuropeLinuxDynamicPlan (Consumption: 0 Small). Is a more expensive plan better in this respect or is the only option to choose the dedicated plan?

**Comment by maiqbal11** [comment] 2018-10-29 23:04
Related to issue https://github.com/Azure/azure-functions-host/issues/3618. Fix will be released tomorrow

**Closed by maiqbal11** 2018-10-29 23:04 UTC
Labels: bug

**Comment by tjhgit** [comment] 2018-10-30 07:47
Do I have to do anything on my end. Like re-deploy or will the bug fix happen automatically?

**Comment by maiqbal11** [comment] 2018-11-01 18:21
> @maiqbal11 Do I have to do anything on my end. Like re-deploy or will the bug fix happen automatically?

You shouldn't need to do anything. The fix will be rolled out soon (should be within the next few days).

**Comment by zsoltbalint** [comment] 2019-09-10 10:14
Was this released since then?

**Comment by maiqbal11** [comment] 2019-09-10 17:38
@zsoltbalint, yes, this should be out now.
