### ISSUE TITLE
Python Functions overwrites Custom Dimensions in logs sent to App Insights

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#694] opened 2020-06-18 06:37 UTC
Steps to reproduce

- Create an Azure Python Function that is connected to Application Insights.

- Create a log message (via logger.Info) and set a customDimension (see opencensus example here: https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/examples/logs/properties.py)

- Look at the message in App Insights and notice that customDimensions is overwritten by Azure.

**Comment by NazariyIvasyuk-Hayfin** [comment] 2021-03-05 07:33
Guys, is there any progress with this bug? I struggle with it too.

**Comment by christoffer-hk** [comment] 2021-03-08 12:37
I am also encountering this problem and would love a fix for this.

**Comment by Hazhzeng** [comment] 2021-03-09 17:59
We're currently under active development on opencensus integration to Python Worker.
Meanwhile, please try using the following snippet code to manually integrate opencensus custom dimension into your Python function app.

```python
import json
import logging
import requests

import azure.functions as func

from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.trace import config_integration
from opencensus.trace.samplers import ProbabilitySampler
from opencensus.trace.tracer import Tracer
from opencensus.trace import execution_context
from opencensus.trace.propagation.trace_context_http_header_format import TraceContextPropagator

config_integration.trace_integrations(['logging'])

# instrucment_key = os.getenv('APPINSIGHTS_INSTRUMENTATIONKEY')
exporter = AzureExporter(connection_string='InstrumentationKey=')
handler = AzureLogHandler(connection_string='InstrumentationKey=')
logger = logging.getLogger(__name__)
logger.addHandler(handler)

def main(req: func.HttpRequest, context: func.Context) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    span_context = TraceContextPropagator().from_headers({
        "traceparent": context.trace_context.Traceparent,
        "tracestate": context.trace_context.Tracestate
    })
    tracer = Tracer(
        span_context=span_context,
        exporter=exporter,
        sampler=ProbabilitySampler(1.0)
    )
    execution_context.set_opencensus_tracer(tracer)

    logger.warning('Before the span')
    with tracer.span("custom_dimensions_span"):
        properties = {'custom_dimensions': {'ABCD': 'EFG'}}
        logger.info('inside the span', extra=properties)
    logger.warning('After the span')

    return json.dumps({
        'method': req.method,
        'ctx_func_name': context.function_name,
        'ctx_func_dir': context.function_directory,
        'ctx_invocation_id': context.invocation_id,
        'ctx_trace_context_Traceparent': context.trace_context.Traceparent,
        'ctx_trace_context_Tracestate': context.trace_context.Tracestate,
    })

```

**Closed** 2021-03-10 00:25 UTC
Labels: needs-triage (functions)

**Comment by Anmol007** [comment] 2021-05-11 17:25
Hi @lzchen @Hazhzeng, I tried the [above example](https://github.com/Azure/azure-functions-python-worker/issues/694#issuecomment-794238606) with ServiceBusTrigger (keeping all the same) but it leads to duplicate traces (pls refer to the image below). 

When I remove the explicit addition of `AzureLogHandler` by removing `logger.addHandler(handler)`
 (as pointed by @brettsam in his [comment](https://github.com/Azure/azure-functions-host/issues/1431#issuecomment-712280268) to avoid double logs) then the traces are not duplicated but custom_dimensions information is lost (pls refer to the image below)

How to avoid the log duplication here while retaining the custom_dimensions property set in the python script?

![image](https://user-images.githubusercontent.com/8396634/117855383-b95c5880-b28a-11eb-9fe7-f8e72799d5e3.png)

**Comment by Hazhzeng** [comment] 2021-05-11 21:33
Hi @Anmol007, 

This is due to a behavior where the root logger has a default handler sending logs to application insight.
So right before the line `config_integration.trace_integrations(['logging'])`. You can clear out the default logging by inserting the following two lines:
```python
root_logger = logging.getLogger()
root_logger.handlers = []
```

**Comment by Anmol007** [comment] 2021-05-11 22:23
> Hi @Anmol007,
> 
> This is due to a behavior where the root logger has a default handler sending logs to application insight.
> So right before the line `config_integration.trace_integrations(['logging'])`. You can clear out the default logging by inserting the following two lines:
> 
> ```python
> root_logger = logging.getLogger()
> root_logger.handlers = []
> ```

Hi @Hazhzeng, I tried the solution you proposed. However I still see double logs (only difference now is that there is no operationName, operationId and customDimensions.Category value changed from Function.ServiceBusTopicTrigger to 
Host.Function.Console). Is this expected?
Note:  I am able to reduce one duplication by moving the `logger.addHandler(handler)` inside main i.e making it local. Could you help me explain why this is leading to one less log entry and is it recommended this way?

![image](https://user-images.githubusercontent.com/8396634/117891676-9eeca400-b2b7-11eb-97e9-df2ec26fc373.png)

**Comment by thatscotdatasci** [comment] 2021-05-20 15:28
I was able to remove the duplicates using:

```python
if (logger.hasHandlers()):
    logger.handlers.clear()
```

However, as shown in @Anmol007's screenshots, the `AzureLogHandler` traces have several different field values - `operation_Id`, `operation_ParentId`, etc. The root logger is `AsyncLoggingHandler` in the `azure_functions_worker` library - why can this not be updated to accept custom dimensions?

**Comment by pacorreia** [comment] 2021-06-02 13:15
I stumbled upon same issue as @thatscotdatasci.

The AsyncLoggingHandler seems to be incomplete, and I could not find a way to override it yet.

will this require some contact with PG to speed up things?

**Comment by frankShih** [comment] 2021-06-30 13:40
I'm facing a similar [issue](https://stackoverflow.com/questions/68195596/opencensus-azure-handler-create-duplicate-log-on-azure-function-apps).

Is there any workaround yet?

**Comment by akulo** [comment] 2021-11-11 16:55
@Hazhzeng is there fix for this problem? I am having same problem

**Comment by salman2learn** [comment] 2022-05-03 13:28
So there are two issues:
1. The custom dimensions are getting overwritten for azure func code.
2. Using above code from @Hazhzeng, we are still seeing duplicate logging.

Can this issue be opened until its fixed at a proper priority?
Is there anyway we can help?

Thanks.

**Comment by matkozak** [comment] 2022-07-08 08:10
Is this still an problem? This issue is closed and so is https://github.com/Azure/azure-functions-python-worker/issues/788, but I don't seem to be able to save custom dimensions using the standard suggested method.

The most frustrating part is that the [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python) makes it sound like a standard procedure. It would be nice to know whether this feature is actually working as expected; if not, can this issue be re-opened or documentation amended to reflect the current state of things?

**Comment by jasperpaalman** [comment] 2022-08-04 12:14
I'm also having this issue, there's no way for me to add custom dimensions. I can remove the root logger handler, which is presumably the `AsyncLoggingHandler`, but still I can't get the custom dimensions working. Even if I would, you would lose the connection between traces that belong to the same function invocation.

Is there any fix for this?

**Comment by thomasnal** [comment] 2022-08-08 13:54
Logging to "custom_dimensions" does not work for us either.  Confirmed just now.  The sample from the documentation does not work.

```
import logging

logger = logging.getLogger(__name__)
// AzureLogHandler initialiazed by Azure Function App environment variable

properties = {'custom_dimensions': {'key_1': 'value_1', 'key_2': 'value_2'}}

logger.warning('action', extra=properties)
```

**Comment by MarthinusBosman** [comment] 2023-08-21 07:28
> We're currently under active development on opencensus integration to Python Worker...

Any progress on that active development 2 years later?

All the issues about this seem to be closed though the problem has never been solved.

**Comment by WaterKnight1998** [comment] 2023-09-28 08:01
Any updates here, I am also seeing duplicate logs :(

**Comment by wiseskus** [comment] 2023-10-16 22:28
As of 10/16/2023, it seems that the issue has not been fixed. customDimensions logged in an Azure functions are not showing in App Insight traces

    properties = {'custom_dimensions': {
        'key_1': 'value_1', 'key_2': 'value_2'}}

    logging.info(
        'test',
        extra=properties
    )

Shows:

customDimensions {"HostInstanceId":"e5121470-c5a1-4596-84fb-72879f1e9185","InvocationId":"25e10fbc-0683-480e-b32c-717815d3a9ab","LogLevel":"Information","ProcessId":"61","Category":"Function.test.User"}

properties = {'key_1': 'value_1', 'key_2': 'value_2'} doesn't work either

**Comment by fredwei888** [comment] 2024-02-03 05:14
We are having the exact same issue, it seems that it is not fixed yet. we used same code above to add custom dimensions log in Azure Function, and they are not shown in the App Insight traces. Any suggestion or solution?

**Comment by kurt-mueller-osumc** [comment] 2024-06-26 20:00
Yea, this is for sure either a bug or the documentation needs to be updated.

**Comment by konstantinmiller** [comment] 2024-07-08 08:34
Still doesn't work, as far as I can see. Please reopen the issue. Or do you prefer that I create a new ticket that duplicates this?

I'm am not explicitly using OpenTelemetry but just grab a standard Python logger. It gets implicitly routed to App Inisights, which is nice. However, the `extra` fields seems to be overwritten and doesn't show up.

This is how I am appending `extra` fields to my log messages

```python
class LogInjector(Mapping):
    static_fields = {
        'your_static_field': 'static_field',
    }
    # you can also add a list with keys for dynamic fields you want to inject
    # you need to then compute the values for them in the __getitem__ method

    def __getitem__(self, item: str) -> str:
        return self.static_fields[item]

    def __iter__(self):
        return iter(self.static_fields)

    def __len__(self):
        return len(self.static_fields)

class LoggerAdapter(logging.LoggerAdapter):
    def process(self, msg, kwargs):
        kwargs['extra'] = {**self.extra, **kwargs.get('extra', {})}  # merges with the, potentially already existing, extra argument
        return msg, kwargs

def get_logger(name):
    logger = logging.getLogger(name)
    logger = LoggerAdapter(logger, extra=LogInjector())
    return logger
```

**Comment by nhtgl** [comment] 2024-07-16 07:37
I'm guessing y'all have a problem with a StreamHandler (the default one). Please let us know. 

I can tell ya if y'all start using logging with open telemetry you'll be able to send your own extra to Application Insights. See my examples here: https://github.com/macieyng/otel-examples/blob/main/examples/simple_instances_example.py

Yep, logging is still "unstable", but it does work. 

As per duplicating logs: use correct namespace for application logs (ie. `app`, `app.something` ) and then make sure that `propagate` is set to `False`. 

So (pseudo code)
```python
import logging
from opentelemetry.sdk._logs import LoggingHandler

logger = logging.getLogger("app")
logger.propagate = False
logger.handlers.clear()
logger.addHandler(LoggingHandler())
```

Learn about logging flow: https://docs.python.org/3/howto/logging.html#logging-flow
