### ISSUE TITLE
Output logging

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-functions-python-worker#77] opened 2018-03-13 04:21 UTC
Hey,

I'm trying to use the new Python runtime and managed to get to a point where I'm now running python 3.6.4, I managed to install dependencies via `requirements.txt` and my function runs. This was already quite a bit of trial and error.

However, I can't seem to get the function to log anything to the output stream.

```
import json
import requests
import os

def main(req):
    postreqdata = json.loads(open(os.environ['req']).read())
    print(postreqdata)
    logger.info(postreqdata)
    logger.info("hey")
```

The output only shows
```
2018-03-13T04:17:31.125 [Info] Function started (Id=296e75cd-1cf1-45cd-80f9-9d8599513db6)

2018-03-13T04:17:33.297 [Info] Function completed (Success, Id=296e75cd-1cf1-45cd-80f9-9d8599513db6, Duration=2179ms)
```

Any pointers?

Thanks!

**Comment by 1st1** [comment] 2018-03-13 04:24
Can you try `logger.error('hey')`?

**Comment by davidobrien1985** [comment] 2018-03-13 04:30
Same outcome.

**Comment by davidobrien1985** [comment] 2018-03-13 04:48
So, I do anything with `logger...` and it doesn't do anything.

I do:

```
def main():
    postreqdata = json.loads(open(os.environ['req']).read())
    print(postreqdata)
```

and it does nothing.

I do:

```
postreqdata = json.loads(open(os.environ['req']).read())
print(postreqdata)
```
without the `main` and it prints out as expected.

I add
`logger.info("hey") to that working snippet and get
```
2018-03-13T04:47:22.927 [Error] Exception while executing function: Functions.github. Microsoft.Azure.WebJobs.Script: Traceback (most recent call last):

  File "D:\home\site\wwwroot\github\run.py", line 10, in <module>

    logger.info("hey")

NameError: name 'logger' is not defined
```

**Comment by 1st1** [comment] 2018-03-13 04:51
Ah, right, you have to define the `logger` variable:

```python
import logging
logger = logging.getLogger('my function')

# later
logger.info(...)
```

**Comment by davidobrien1985** [comment] 2018-03-13 04:55
Well, that's not throwing any errors any more, but also no output.

I assume `'my function'` is the name of the function?
So if my function is called `davidstest` then
`logger = logging.getlogger('davidstest')`

and then `logger.info("hey")` should work?

No output for me. Same with `.error`

**Comment by 1st1** [comment] 2018-03-13 05:12
Can you try `logging.error`?  `logging.info` has a low priority and might not be displayed (which is a bug and will be fixed)

**Comment by davidobrien1985** [comment] 2018-03-13 05:16
No luck.

This is the complete function:
```
import json
import os
import logging

logger = logging.getLogger('github')

logging.error("hey")
logger.error("hey")
postreqdata = json.loads(open(os.environ['req']).read())
print(postreqdata)
```

and the output is:
```
2018-03-13T05:15:34.981 [Info] Function started (Id=6691560c-9814-4623-9b80-1fa75670af88)

2018-03-13T05:15:35.247 [Info] {u'name': u'newrepo'}

2018-03-13T05:15:35.247 [Info] Function completed (Success, Id=6691560c-9814-4623-9b80-1fa75670af88, Duration=262ms)
```

**Comment by 1st1** [comment] 2018-03-13 06:20
I've created PR #78 to preconfigure the logging system to log messages starting with `INFO` level and also fixed a related bug.  Please try it, it might fix things on your machine.

**Comment by davidobrien1985** [comment] 2018-03-13 06:21
about to take off from LAX to Brisbane now.
Will test in 15hrs 😉
Thanks so far!

Sent from my iPhone

On 12 Mar 2018, at 11:20 pm, Yury Selivanov <notifications@github.com<mailto:notifications@github.com>> wrote:


I've created PR #78<https://github.com/Azure/azure-functions-python-worker/pull/78> to preconfigure the logging system to log messages starting with INFO level and also fixed a related bug. Please try it, it might fix things on your machine.

**Comment by 1st1** [comment] 2018-03-13 06:21
BTW, how did you configure your environment? Did you follow https://github.com/Azure/azure-functions-python-worker/wiki/Setting-up-development-environment?  If no, could you please create a new environment following that wiki page?

**Comment by 1st1** [comment] 2018-03-13 06:22
Have a good flight :)

**Comment by 1st1** [comment] 2018-03-13 16:13
The PR has been merged to the `dev` branch.

**Comment by asavaritayal** [comment] 2018-03-14 20:13
@christopheranderson Do we need to update the Python image to reflect these changes?

**Comment by asavaritayal** [comment] 2018-03-18 02:00
Reopening the issue since I'm still not seeing any logs.

**Comment by davidobrien1985** [comment] 2018-03-18 10:37
@1st1 sorry, took me a few days to get back to this.
I also still don't see any log output.

I created the Function via the portal by creating an "experimental python" function. All I did was follow the portal to create the function, nothing else. 
If the expectation is that users need to do more or something else then please remove the ability to create a python function via the UI.

**Comment by 1st1** [comment] 2018-03-19 17:39
> Reopening the issue since I'm still not seeing any logs.

@asavaritayal What branch are you running your code on? `dev`? Could you please share your function's code?


@davidobrien1985

> I created the Function via the portal by creating an "experimental python" function. All I did was follow the portal to create the function, nothing else.

The portal doesn't run the latest code, please give it some time.  We haven't even started any testing of the new worker officially.

> If the expectation is that users need to do more or something else then please remove the ability to create a python function via the UI.

Please keep in mind that this repo is WIP.  How exactly users should use this repo outside of the portal is still being worked on.

**Comment by asavaritayal** [comment] 2018-03-29 20:55
I can confirm that logging works with the latest build. 

@davidobrien1985 Just to clarify, we’re speaking about two different flavors of Python support in Functions.
 
V1 – Python support for the v1 runtime is experimental. It’s not recommended or ready for production scenarios. We’ll be deprecating it sometime this year. (I think this is the one you're currently trying.)

V2 – This repo is for first class Python support on the v2 runtime. Currently in development, we’ll have a preview release in the next couple of months.

**Closed by asavaritayal** 2018-03-29 20:55 UTC

**Comment by anuj607** [comment] 2020-05-08 11:53
I am not able to debug the function app in Python. there is no console and no log thing ..
When i simply type this in cmd
az webapp log tail --resource-group <resGrp> --name <func app in python>


Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2050, in _get_log
knack.util.CLIError: **Failed to connect to 'https://<appname>.scm.azurewebsites.net/logstream' with status code '404' and reason 'Not Found'**

**Comment by balag0** [comment] 2020-05-09 18:28
@anuj607 Please open a new issue since this is already closed. Include what type of app you are using consumption/premium/etc..

**Comment by chronoclast** [comment] 2021-02-08 16:55
Hi @asavaritayal,
Still no logs, independently of the log level 😢 
I can confirm that **they don't show up on the Log Stream** feature on the Azure portal, and **using the CLI command fails** with the same error @anuj607 posted last year.
Any solution? Thanks!

**Comment by corticalstack** [comment] 2021-11-09 11:53
Did you ever get this resolved? Same issue, using logging I can't see any output from logging in teh Azure functions log stream. Thanks

**Comment by SantoshDMore** [comment] 2022-05-24 20:49
I am also facing the same issue. Dont see any output from logging. 
I tried following but no luck. 
logger = logging.getLogger('my function')
logger.info(...)
