### ISSUE TITLE
How to Verify Running Function Instance Count During Scale Out?

### ISSUE THREAD

**Issue by ericdrobinson** [Azure/azure-functions-python-worker#359] opened 2019-03-09 18:04 UTC
I'd love to verify the number of Azure Python Function instances that are spawned and running at once. From anecdotal evidence, it _looks_ like I'm only able to get one instance to start at a time. This would seem to imply that the Linux Consumption Plan doesn't properly scale as [the documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale) would suggest.

The _one_ bit of information that I've seen about limitations with Linux Consumption Plans is over on [this GitHub Wiki page](https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-on-Linux-Preview):

>Please note during the early preview timeframe scale for a function app is limited to 2 instances.

That said, the page is now several months old and I cannot find any other information that corroborates the limitation.

Is scale-out of Azure Functions on Linux (and, more specifically, Azure **_Python_** Functions on Linux) expected to work at this time? If so, how are we expected to inspect the status of scale-out functionality to verify that things are working according to expectations?

**Comment by ericdrobinson** [comment] 2019-03-12 15:48
Any information on this would be greatly appreciated. From watching the log flow in the Function's Monitor tab on the Azure Portal it _**really**_ looks like there's only a single instance running at a time, which would be... problematic.

I fear that I'm doing something to stop scale-out and yet I can't even figure out if scaling is working at all, let alone how to troubleshoot what may be stopping it...

**Comment by maiqbal11** [comment] 2019-03-12 16:27
@ahmelsayed, @balag0, how can we verify the scale out behavior of the application? Do we have logs or some other mechanism?

**Comment by balag0** [comment] 2019-03-12 17:25
@ericdrobinson Please share the sitename.

**Comment by ericdrobinson** [comment] 2019-03-12 19:41
@balag0 I'm so not interested in sharing it here in public. Please provide an email address to which I can send the name of the Function app.

**Comment by JK87iab** [comment] 2019-03-12 20:07
I use azure app insight, on the live metric tab you can see number of servers running.

In the past I only see a maximum of 2 servers. Right now I can actually see 4 servers running.

**Comment by ericdrobinson** [comment] 2019-03-12 20:24
@JK87iab What is the "Live Metric Tab" of which you speak?

**Comment by ericdrobinson** [comment] 2019-03-12 20:36
Is it the "Live Metrics Stream"? If so, then I've located it. I see in the top-left corner that it says "**2** servers online".

The whole display is really odd there... only Request Rates values actually show anything. There is no information whatsoever in the Outgoing Requests or Overall Health sections. Is that normal?

**Comment by JK87iab** [comment] 2019-03-12 20:50
@ericdrobinson  Yes that the correct one. I get 4 servers online, which is new for me too, in the past I only got a maximum of 2.

overall health doesn't show anything for me either. I am using a pay by execution plan.

**Comment by ericdrobinson** [comment] 2019-03-12 21:08
I'm going to drop my `maxConcurrentRequests` to something super low to see what, if any, affect it has on things.

The lack of any memory/CPU reporting here is worrisome. Could it be that the dynamic scaling doesn't work because the autoscale system is simply seeing constant zeros from each instance? But, at the same time, what else would trigger the second instance to start up?

**Comment by balag0** [comment] 2019-03-12 21:36
@ericdrobinson Can you try these instructions and share the Execution Id
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

Is this a http function you are trying to scale?

**Comment by ericdrobinson** [comment] 2019-03-12 22:05
@balag0 Thanks! Responses below:

>Can you try these instructions and share the Execution Id
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

So apparently that resource is out of date? I saw no logs that matched the formatting suggested in the above resource. What's more, any reported UUIDs appeared to be for the purpose of tracking specific invocations of the function...

Is there another way I can get you that Execution ID? Or... are those invocation UUIDs the Execution ID you're looking for?

>Is this a http function you are trying to scale?

Yes.

**Comment by balag0** [comment] 2019-03-12 22:08
Yes. You are right , the log format might have changed a bit. But the GUID is what we are looking for. 
Something like 

Executing 'Functions.http' (Reason='This function was programmatically called via the host APIs.', Id=**_a3ca600c-975d-4bfa-8234-0de584015679_**)

**Comment by ericdrobinson** [comment] 2019-03-12 22:08
Let me answer my own question:

>Or... are those invocation UUIDs the Execution ID you're looking for?

Yes. That is the case. Here is some sample information for you:

* **Execution ID:** bddd5bcc-a482-4283-b54d-09695c7af6e5
* **Execution Time:** 2019-03-12 21:57:55.782
* **Region:** USEast

**Comment by ericdrobinson** [comment] 2019-03-12 22:24
@JK87iab Does your app have two Functions perhaps? Could it be that the 2 instance limit is per-function, rather than per-app?

**Comment by JK87iab** [comment] 2019-03-13 01:47
@ericdrobinson 
Nope its one functions getting triggered by a message in a storage queue.  Since python support is still in preview I guess they limit the scalability as off now.

**Comment by balag0** [comment] 2019-03-13 02:25
Just to add some information on the current state of scaling while we are in preview.
Each app is limit is restricted to 2 instances max by default. This is at the app level not the function level. Number of functions in the app doesn't impact the number of instances the app scales to. 

@ericdrobinson Did the function execution succeed, I can't seem to locate your site based on the guid. 
Please email  linuxazurefunctions [at] microsoft.com and we will investigate this further.

**Comment by ericdrobinson** [comment] 2019-03-13 16:10
@balag0:

>Just to add some information on the current state of scaling while we are in preview.
Each app is limit is restricted to 2 instances max by default. This is at the app level not the function level. Number of functions in the app doesn't impact the number of instances the app scales to.

Thanks for the rundown. It's good to get some clarification. Helps me consider how best to take what I'm learning about performance characteristics and devise a more efficient solution.

>Did the function execution succeed, I can't seem to locate your site based on the guid.
Please email linuxazurefunctions [at] microsoft.com and we will investigate this further.

It did, but I may have sent you the results of a live run, rather than something that was run through the Portal (that Portal interface works for me ~50% of the time; the JavaScript console is always rife with errors [I'm on Chrome 72]). Perhaps that's the reason?

Regardless, I've sent an email with the Function App name to the email address you specified.

**Comment by ericdrobinson** [comment] 2019-03-13 16:13
>The lack of any memory/CPU reporting here is worrisome. Could it be that the dynamic scaling doesn't work because the autoscale system is simply seeing constant zeros from each instance? But, at the same time, what else would trigger the second instance to start up?

The following image shows what I'm referring to in the above paragraph:
![image](https://user-images.githubusercontent.com/9142587/54295291-182dc680-4589-11e9-9b6d-4f8067c3b14c.png)

There's no data other than what is found in the **Incoming Requests** section. Is this expected? Why wouldn't I be getting any information on CPU/memory usage?

**Comment by balag0** [comment] 2019-03-14 19:45
@ericdrobinson Got your sitename. I see it did scale to 2 instances and was throttled after that. 
So the 2 servers online from the dashboard seems correct.

Azure portal is misleading, since it will only connect to one instance at a time currently even if you have multiple instances.

As for why CPU and Memory is missing, we need to investigate. I opened this issue to track this - https://github.com/Azure/Azure-Functions/issues/1148

**Comment by ericdrobinson** [comment] 2019-03-14 20:02
>Azure portal is misleading, since it will only connect to one instance at a time currently even if you have multiple instances.

Oh man. Is that something that could be communicated? It's pretty huge in terms of understanding/reading the metrics!

>As for why CPU and Memory is missing, we need to investigate. I opened this issue to track this - Azure/Azure-Functions#1148

Awesome, thanks very much. It's good to know that we _should_ be seeing those. Those metrics not working has had me wondering what I've done to break my function and reaching out to various channels to figure out what's going on...

**Comment by balag0** [comment] 2019-03-14 21:16
Just want to make sure we are talking about the same thing. Portal connecting to just 1 instance is specific to logging. Metrics should still work with multiple instances. I will add this information also the tracking issue.

Yes, Not having the cpu and memory metrics is a bug.

**Comment by ericdrobinson** [comment] 2019-03-14 21:32
Was about to ask for clarification on which interface you were referring to with respect to the logging. Saw on the tracking issue that you were referring to the Functions Monitor tab. I assume that's this:
![image](https://user-images.githubusercontent.com/9142587/54392902-23fbb480-467f-11e9-8749-c664d476b398.png)
Yeah?

**Comment by ericdrobinson** [comment] 2019-05-08 14:58
For the past several weeks we have noticed that the Live Metrics system reports the existence of only a single server. The server name field is now "(none)" and the "Application map" seems to also verify that we only ever see a single server up at a time ("1 instance").

When I opened this bug [we were able to see](https://github.com/Azure/azure-functions-python-worker/issues/359#issuecomment-472170919) that 2 servers were up and even get their names.

Did something break? We expect to be able to scale out to at least 2 instances during the Preview though it appears that we're stuck with a maximum of 1 instance at present.

[We have rearchitected our application since I opened this issue such that there are now _two_ functions: one HTTP trigger and one Queue trigger. We made this change back in March and everything continued to work, scaling to 2 servers under load as expected.]

**Comment by bigdatamoore** [comment] 2019-05-23 13:59
I am seeing the same thing as @ericdrobinson.  Prior to several weeks ago, I used to see multiple linux servers running our python functions in the live metrics stream, but now I am only seeing one row with a name of "(none)" under the servers list.  We have some Windows servers as well in the same app insights, and those show up in the server list with all their info.   Can someone from the functions team confirm what the expected behavior should be here?  I would like to be able to at least know the accurate number of servers that are online at a given time.

**Comment by bigdatamoore** [comment] 2019-05-29 18:25
Any update on this?

**Comment by balag0** [comment] 2019-05-30 00:05
Sorry. have been busy with couple of other issues. I will try get an update in the next couple of days.

**Comment by balag0** [comment] 2019-06-16 22:59
Update - Identified the issue. Working on a fix now.

**Comment by ericdrobinson** [comment] 2019-07-15 21:41
@balag0 Any update on this issue? We're still seeing "**(none)**" for the name.

Limited testing also shows that we're only "scaling" to 1 server online at a time as well...

**Comment by balag0** [comment] 2019-07-19 18:15
We are hoping to include the fix as part of the next functions release starting sometime next week. 
How are you identifying that the app is scaling to 1 instance?

**Comment by ericdrobinson** [comment] 2019-07-19 19:14
>How are you identifying that the app is scaling to 1 instance?

By watching the Live Metrics Stream. It only ever reports "1 servers online":

![image](https://user-images.githubusercontent.com/9142587/61559048-c74a4500-aa36-11e9-9d42-11fd05568eac.png)

And only ever shows a single server in the server list:

![image](https://user-images.githubusercontent.com/9142587/61559081-d4ffca80-aa36-11e9-85af-d22f1b4a71e6.png)

(I ran the system up to an average of ~10 reqs/sec over the course of a couple of minutes, sending it a few hundred/thousand total reqs. This generates a sizable queue for the function to process. However, The Live Metrics Stream only ever shows 1 server running.

It _**used**_ to scale up to two servers. However, we've not seen that for a while.

I should also point out that our current function was built and pushed live back on May 1st. If this has implications on how the function scaling works, it would be extremely helpful to know that.

**Comment by balag0** [comment] 2019-07-19 19:17
Right. The data available on live metrics is not reliable (which is being fixed next week). So it is expected it will only show 1 instance until then.
It is likely the issue is not with scale but with the dashboard.

**Comment by ericdrobinson** [comment] 2019-07-19 19:58
Got it! Is there any _other_ way to verify function scaling?

**Comment by balag0** [comment] 2019-08-12 22:49
The fix is deployed now. You can get the instance count using the following query in appinsights

requests
| where timestamp >= ago(1h)
| distinct cloud_RoleInstance, appName

(If your app has been running continuously you might need to restart the app to get the latest updates)

Let me know if that helps. Thanks for your patience.

**Comment by ericdrobinson** [comment] 2019-08-13 20:19
@balag0 Unfortunately, I'm not terribly familiar with the appinsights system. Where exactly would I commit the query you suggested? Any documentation you could point me towards, perhaps?

**Comment by ericdrobinson** [comment] 2019-08-13 20:29
Nevermind! I found it. The query is intended to be run against [Log Analytics](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/get-started-portal). It appears to work, too!

The Live Metrics Stream appears to still only report a single server, even though it looks like more are spawned based upon the output from the log analytics query. Is this to be expected? When will the Live Metrics Stream support proper reporting of server instances?

**Comment by balag0** [comment] 2019-08-13 20:40
Great. Yes. I think there is some issue with the live metrics stream where it seems to connect to only 1 server at a time. 

I opened an issue and will follow up on what is different with the live metrics view.
https://github.com/Azure/Azure-Functions/issues/1301

I think we can close this issue though since the instance count is available from log analytics.

**Comment by ericdrobinson** [comment] 2019-08-13 20:44
That sounds fine by me.

I wish there were a more direct way to do it, beyond needing to know the esoteric query, but at least this issue will live on to provide others with helpful breadcrumbs...

Thanks for helping find/build a solution!

**Closed** 2019-08-13 20:46 UTC
Labels: func-stack: Python, platform:linux

**Comment by balag0** [comment] 2019-11-08 02:03
This is fixed in the live metrics page now - https://github.com/Azure/Azure-Functions/issues/1301
Please give it a try.

**Comment by ericdrobinson** [comment] 2019-11-08 15:28
While it is difficult for us to validate the fix due to [this issue](https://github.com/Azure/azure-functions-host/issues/5200), we were still able to see our function app scale out to 3 servers.

We anticipate that the Live Metrics will gain a lot more value once the fix for the CORS bug is live.

Thanks very much for implementing this!

**Comment by dc799** [comment] 2019-11-12 08:32
@ericdrobinson - Thanks for the breadcrumbs. We're currently doing scale testing and the functions appear to be a bottleneck. We know they're capable of scaling but it's hard to get a visual on it. Hopefully they can come up with a nicer view of how many instances are currently running.

**Comment by balag0** [comment] 2019-11-12 19:41
@dc799 Feel free to open a new issue and provide more details on the scaling issues you are noticing. Would be good to make sure it is only a visualization issue. 
Would also like to hear more about any improvements we could make to the live metrics stream.
