### ISSUE TITLE
Isolate customer's code from Python worker process

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-functions-python-worker#616] opened 2020-02-06 23:28 UTC
#### Story
Previously, a broken third-party package **pmdarima==1.5.1** has a dependency on pathlib==1.0.1. The pathlib library meets end of its life and it **collides with Python builtin pathlib library**, raising Proxy Path issue when importing customer modules, which breaks our Python worker.

#### Repro steps

1. Create a function app with single HttpTrigger.
2. In requirements.txt, put in a broken library: **pathlib==1.0.1**
3. Publish the function app into App Service Plan (which doesn't do placeholder environment reload), the HttpTrigger returns 500, the whole function app is down.

#### Possible design improvement

Separate Python worker environment from customer's code.
Customer's code should only have effect on their own functions.

This valuable feedback is provided by @AnatoliB

**Comment by Hazhzeng** [comment] 2020-07-20 23:51
cc: @anirudhgarg @vrdmr

**Comment by vrdmr** [comment] 2021-02-01 02:39
@Hazhzeng - Would #794 also solve this issue? More specifically #789 a duplicate of this issue?

**Comment by stefanushinardi** [comment] 2021-04-27 00:23
@Hazhzeng is this done?

**Closed** 2021-04-28 21:20 UTC
Labels: needs-discussion
