### ISSUE TITLE
[BUG] Failure due to memory exhaustion does not log an exception to App Insights

### ISSUE THREAD

**Issue by wallflower762** [Azure/azure-functions-python-worker#1128] opened 2022-10-24 02:38 UTC
### Investigative information
- Timestamp: 10/2022 10:05AM UTC
- Function App name: prd-imt-analytics-functions
- Function name(s) (as appropriate): func_queue_rock_clustering
- Functions runtime: ~4
- Python version: 3.8

One of my functions failed due to memory exhaustion. No exception was logged to App Insights. I can see the exception when using the function app diagnostic tools

### Repro steps
1. Create a function app with an excessive memory usage requirement
2. Deploy the function app to an App Service plan with App Insights logging enabled
3. Run the function until invocation has completed
4. Check App Insights exceptions table
5. Check function app diagnostics blade `Function Executions and Errors` to confirm the failure

### Expected behavior
An exception is found in App Insights that matches the exception in the diagnostics section.

### Actual behavior
No exceptions are found in App Insights while the diagnostics tab has the exception correctly logged:
![image](https://user-images.githubusercontent.com/81551380/197437591-660cf058-b574-43c9-be31-e5e4010b5882.png)

### Known workarounds
None

### Contents of the requirements.txt file:
azure-functions==1.8.0
azure-functions-durable==1.1.3
azure-storage-blob==12.5.0
azure-storage-queue==12.1.6
azure-data-tables==12.2.0
azure-servicebus==7.8.0
azure-identity==1.6.1
numpy==1.19.2
pandas==1.1.2
pymongo==3.11.2
dnspython==2.0.0
scipy==1.6.0
matplotlib==3.3.3
kneed==0.7.0
scikit-learn==0.24.0
json-logging==1.2.11
requests==2.25.1
flake8==3.8.4
black==22.3.0
seaborn==0.11.1
pykalman==0.9.5
pyarrow==4.0.1
PyWavelets==1.1.1
minisom==2.2.9
adtk==0.6.2

### Related information
I recently changed from synchronous functions to async functions. I used to correctly receive exceptions in App Insights for memory exhaustion issues, so I wonder if this change is related. I noticed [this](https://github.com/Azure/azure-functions-python-worker/issues/898) issue already, but am not sure if it's related.

Function app is deployed to a P3V3 App Service plan as a docker container. Multiple functions are deployed to the function app with various profiles of memory, CPU usage, and network IO. I have just talked about a single function that is the most memory intensive for the purpose of this issue.

Base image: mcr.microsoft.com/azure-functions/python:3.0-python3.8-slim

**Comment by YunchuWang** [comment] 2022-10-31 15:15
@ramya894 Hello can you share the code and I left a comment in issue #898 containing example of async function using event which sends logs to appinsights. thank you

**Comment by ramya894** [comment] 2022-11-02 14:40
@wallflower762 Please go through the discussion in the below link for more information on this issue.

https://github.com/Azure/azure-functions-python-worker/issues/898

**Comment by wallflower762** [comment] 2022-11-02 14:41
Thanks for the reply, I should have time to have a look through next week.

**Comment by Akithaj0528** [comment] 2023-06-12 08:45
@wallflower762 we have provided the required information, is there any other information needed.

**Comment by wallflower762** [comment] 2023-06-12 09:22
Hi @Akithaj0528, sorry I haven't had time to test.

**Comment by Akithaj0528** [comment] 2023-06-12 14:19
Hi @wallflower762,
When is the ETA as the issue is open for a long time now, can we close it for now and we can reopen again if we find any issue. Kindly let us know.

**Closed** 2023-06-19 18:01 UTC
Labels: needs-author feedback, no recent activity
