### ISSUE TITLE
Add support for absolute imports

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/azure-functions-python-worker#278] opened 2019-01-10 15:32 UTC
Currently only relative imports are supported for local packages, however that is definitely not the pythonic way to do things. In Python absolute imports are preferred over relative imports.  
Also few things are difficult by just using relative imports:
```py
# file: constants.py
A = "a"
B = "b"

# file: main.py
from .constants import A, B  # works fine
import .constants   # Doesn't work!
```

By this behaviour, Python functions app forces `from ... import ...` syntax which is not always preferred and many times against organization specific style guidelines.

#### Repro steps

Covered above.

#### Expected behavior

Absolute imports should be supported as per python guidelines.

#### Actual behavior
It fails! 

#### Known workarounds
Use relative imports

#### Related information 
On issue #81, relative imports are suggested.

**Comment by fabiocav** [comment] 2019-02-20 21:50
@maiqbal11 moving this to sprint 44 to track the remaining work.

**Comment by maiqbal11** [comment] 2019-02-25 23:14
With #325, `__app__` is the function application's top level module and can be used as an anchor for performing absolute imports.

Taking the following function example:

```
__app__
  Function1
    __init__.py
    func_module.py
  HelperCode
    __init__.py
    helper_module.py
```
We have support for the following sytaxes (as examples):

1. `from __app__ import HelperCode`
2. `from __app__.HelperCode import helper_module`
3. `import __app__.Function1`
4. `import __app__.HelperCode` 

We do not currently have plans to support implicit relative imports of the form `import func_module` from within `Function1.__init__.py`. This is by design as it has the potential to cause conflicts with other libraries that are using the same module name. Explicit relative imports are preferred: `from . import func_module`. 

@asavaritayal, we should be able to document the use of `__app__` and close on this (plus other issue about absolute imports).

**Comment by asavaritayal** [comment] 2019-02-26 17:59
Thanks @maiqbal11 . Assigning myself for documenting.

**Comment by brettcannon** [comment] 2019-03-19 01:46
One key point that I want to make sure gets documented is if you're going to require `__app__` as the top-level directory, then anyone who wants to run their Function code outside of the Function runtime (e.g. CI for unit tests) **must** keep their entire Function directory in an `__app__` folder in order for those imports to resolve appropriately. IOW this will will essentially dictate the folder name that everyone's Function-related files must be kept in if anyone chooses to use absolute imports.

**Comment by Kagigz** [comment] 2019-04-03 10:41
Hello, I keep trying to import a local module into a Python function, without success.

Here's my project structure:

```
functions_python
    |_ ml-service
        | __init__.py
        | model_helper.py
        | function.json
```
I want to import model_helper into init, and here are some of the things I tried:

from . import model_helper (no module named model_helper)
from ..ml-service import model_helper (Invalid syntax)
from functions_python.ml-service import model_helper (Invalid syntax)
import functions_python.ml-service (Invalid syntax)
from __app__.ml-service import model_helper (Invalid syntax)
import __app__.ml-service (Invalid syntax)

I'm using Python 3.7 and not 3.6 - could it be the reason why I can't get this to work?

**Comment by maiqbal11** [comment] 2019-04-03 14:58
Hi @Kagigz, would it be possible to move your description to a separate issue? We can address it there. Just trying to keep this issue focused on what was originally being discussed :)

**Comment by Kagigz** [comment] 2019-04-03 15:08
@maiqbal11 no problem! I've created another issue: [#374](https://github.com/Azure/azure-functions-python-worker/issues/374)

**Comment by asavaritayal** [comment] 2019-06-01 01:30
Addressed in this PR - https://github.com/MicrosoftDocs/azure-docs-pr/pull/78522

**Closed by asavaritayal** 2019-06-01 01:30 UTC
Labels: P0, docs, func-stack: Python

**Comment by dxkaufman** [comment] 2019-11-15 22:16
@maiqbal11 I am having a similar problem, as described in detail in https://github.com/Azure/azure-functions-python-worker/issues/577.  My functions were all working fine as of Oct 31, and without any code changes it is no longer working after upgrading VSC and Azure Functions core tools to the latest versions earlier this week.  I have tried numerous changes, including putting all the code folders under the ```__app__``` directory, to no avail.  Any suggestions you can offer would be greatly appreciated!  Thank you for your time.

**Comment by maiqbal11** [comment] 2019-11-15 23:52
@dxkaufman please open a separate issue with all the details of your case and we can investigate.

**Comment by dxkaufman** [comment] 2019-11-16 01:36
@maiqbal11 i opened issue 577 for it.  Thank you!
