### ISSUE TITLE
Install and import xgboost in Python Azure Function app doesn't work 

### ISSUE THREAD

**Issue by cconcordet** [Azure/azure-functions-python-worker#573] opened 2019-11-04 08:57 UTC
The deployment of a python function on Azure Function app (which works on a local host) doesn't work because of the import of the xgboost package. The error is :
Exception: XGBoostError: XGBoost Library (libxgboost.so) could not be loaded.
Likely causes:

OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libgomp.so for UNIX-like OSes)
You are running 32-bit Python on a 64-bit OS
Error message(s): ['libgomp.so.1: cannot open shared object file: No such file or directory']

This thread adresses the issue : #493

We tried to put the .whl directly in the function folder and install the package from there, which didn't work.

I opened [this thread](https://github.com/MicrosoftDocs/azure-docs/issues/40856) where I was told by @anirudhgarg  to open a new issue here as it seems that the issue comes from the libcomp.so library. 

I was also told by @mike-urnun-msft to open [this thread](https://social.msdn.microsoft.com/Forums/en-US/8582c383-8fe3-49ee-9d95-b3587e893f3c/install-and-import-xgboost-in-the-deployment-of-python-azure-function-app?forum=AzureFunctions) on msdn forum.

Thanks !

**Comment by anirudhgarg** [comment] 2019-11-04 18:07
@cconcordet thanks for opening. Do you by any chance have a sample app that we can try to repro this.

**Comment by cconcordet** [comment] 2019-11-05 09:35
I am sorry I can't share my code but it seems that the error comes from the following line
import xgboost 
I can try to produce a sample if that is not enough information ?

**Comment by cconcordet** [comment] 2019-12-03 08:53
Any updates ?

**Comment by hpahkala** [comment] 2019-12-07 19:58
I have similar problem with lightGBM. 
That is, libgomp seems to be missing in Azure Functions Runtime like in xgboost case.
Code to reproduce libgomp missing problem with lightGBM
```
import logging
import lightgbm
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function to get lightgbm version.')
    lgb_version = lightgbm.__version__
    return func.HttpResponse(f"lightgbm version is {lgb_version}!")
```
requirements.txt:
```
azure-functions
lightgbm
```
Error:
```
Result: Failure
Exception: OSError: libgomp.so.1: cannot open shared object file: No such file or directory
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 242, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/site/wwwroot/HttpTriggerTestFunc/__init__.py", line 2, in <module>
    import lightgbm
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/lightgbm/basic.py", line 33, in <module>
    _LIB = _load_lib()
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/lightgbm/basic.py", line 28, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)


```

**Comment by cconcordet** [comment] 2020-01-06 09:18
Hello @anirudhgarg ,
Any updates ?

**Comment by anirudhgarg** [comment] 2020-01-22 18:30
We have added support for the missing library libgomp.so.1 now. @cconcordet @hpahkala  can you please confirm that it is working for you know.

**Comment by anirudhgarg** [comment] 2020-01-27 02:35
I just tried your app @hpahkala and it works great and I was able to see the following: "lightgbm version is 2.3.1!". I am closing this with this you should be able to use xgboost and lightgbm now.

**Closed by anirudhgarg** 2020-01-27 02:35 UTC
Labels: needs-author feedback, no recent activity, system-deps
