### ISSUE TITLE
Errors when running queueTrigger function from the portal

### ISSUE THREAD

**Issue by logachev** [Azure/azure-functions-python-worker#460] opened 2019-06-13 20:24 UTC
#### Investigative information

Please provide the following:

- Timestamp: 06/13/2019 1:15 PM
- Function App name: kiril-func
- Function name(s) (as appropriate): QueueTrigger
- Core Tools version: 2.7.1373

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create new Function App project in VSTS
2. Create new QueueTrigger function
3. Deploy function
4. Go to the portal and click 'Run'

#### Expected behavior

Show error 'Unable to run queueTrigger function' or block Run button or allow some easy way to edit test data via portal. 

#### Actual behavior

Function crashes with the callstack:
```
2019-06-13T20:16:11.641 [Information] Executing 'Functions.QueueTrigger' (Reason='This function was programmatically called via the host APIs.', Id=ed38142a-3c9e-47cc-be86-cb7e4c2affa5)
2019-06-13T20:16:11.780 [Error] Executed 'Functions.QueueTrigger' (Failed, Id=ed38142a-3c9e-47cc-be86-cb7e4c2affa5)
Result: Failure
Exception: ValueError: time data '9999-12-31T23:59:59.9999999+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 285, in _handle__invocation_request
    pytype=pb_type_info.pytype)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 298, in from_incoming_proto
    trigger_metadata=trigger_metadata)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/bindings/queue.py", line 93, in from_proto
    trigger_metadata, 'ExpirationTime'),
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 149, in _parse_datetime_metadata
    return cls._parse_datetime(datetime_str)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 192, in _parse_datetime
    raise last_error
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 187, in _parse_datetime
    dt = datetime.datetime.strptime(datetime_str, fmt)
  File "/usr/local/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
```

#### Known workarounds

None

#### Related information 

Provide any related information 

* Links to source
* Contents of the requirements.txt file
* Bindings used

<!-- Uncomment this if you want to include your source (wrap it in details to make browsing easier)
<details>
<summary>Source</summary>

```python
import logging

import azure.functions as func


def main(msg: func.QueueMessage) -> None:
    logging.info('Python queue trigger function processed a queue item: %s',
                 msg.get_body().decode('utf-8'))
```

**Comment by balag0** [comment] 2019-06-13 21:35
Is the datetime that the worker trying to parse ( and fail ) coming from your test data? 

Also looks like the issue is not that parsing is failing, but that portal doesn't disable the run button?

**Comment by logachev** [comment] 2019-06-13 21:56
I didn't change anything, so there is no test data.

Yeah, I'm not worried about the failure since for the queue trigger you have to have actual queue event to work. The problem is that there is no way (at least I can't find one) to provide test queue message.

**Comment by balag0** [comment] 2019-06-14 02:36
Sorry, not sure i understand the ask. 
Are you looking for a way to test your queue trigger without using a queue?

**Comment by unstephenk** [comment] 2019-07-04 20:40
I am seeing the same error. I contacted support and waiting to her back. Also found this: https://github.com/Azure/azure-functions-python-worker/pull/399

**Comment by unstephenk** [comment] 2019-07-08 13:50
Support says they are unable to reproduce the error. I have reproduced 3 times already!!

**Comment by unstephenk** [comment] 2019-07-08 13:52
You can test the queue trigger by download Microsoft Azure Storage Explorer -> Find the queue in the navigation -> click add message

**Comment by ShihMeng-Hsu** [comment] 2019-08-04 17:18
I also encounted the same problem.
  Exception: ValueError: time data '9999-12-31T23:59:59.9999999+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

Do you know has this issue been fixed? Or any workround that can skip the problem?  Thanks!!

**Comment by maiqbal11** [comment] 2019-08-05 17:30
@ShihMeng-Hsu, you should be able to use Storage Explorer to write to a test queue or you can also you use an Azure Function with a queue output binding for testing.

**Comment by rajibmitra** [comment] 2019-11-01 09:01
I have getting the same issue 
Exception: ValueError: time data '9999-12-31T23:59:59.9999999+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ' even after using Storage Explorer.

**Comment by wkeithvan** [comment] 2019-11-19 19:12
+1 on this. Also getting that error when manually triggering a timer function with a queue binding output from the portal.

**Comment by dataops-noob** [comment] 2019-11-20 14:09
+1 on this. we are facing the same issue too

**Comment by norbitrial** [comment] 2020-01-10 09:52
+1 We face with the same issue still.

**Comment by anirudhgarg** [comment] 2020-01-11 00:18
Reopening the issue. Doesnt look like the original issue of this not working in the portal was ever solved.

**Comment by vrdmr** [comment] 2020-09-25 01:34
The issue is due to Python's `datetime` datatype inability to support anything finer-grained than microseconds.

https://stackoverflow.com/a/10612166/862941

**Comment by vrdmr** [comment] 2022-03-21 18:43
Fixed by https://github.com/Azure/azure-functions-python-library/pull/95.

**Closed by vrdmr** 2022-03-21 18:43 UTC
Labels: P2
