### ISSUE TITLE
[BUG] Host won't start when adding CONTAINER_NAME as environment variable

### ISSUE THREAD

**Issue by Kagigz** [Azure/azure-functions-python-worker#793] opened 2020-12-13 22:36 UTC
Core Tools version: 3.x (latest)

###### Provide the steps required to reproduce the problem:

1. Create a python function app containing a queue-triggered function
2. Add "CONTAINER_NAME" variable in local.settings.json
3. Run func host start

### Expected behavior

I would expect the function app to start normally. When I add other environment variables named differently, there are no issues.

### Actual behavior

When I have a variable "CONTAINER_NAME" in the settings, I get this error when trying to start the function host:

```
MS_FUNCTION_LOGS 5,,,ProcessDoc,GetMessages,Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener,"","Poll for function 'ProcessDoc' on queue 'processing' with ClientRequestId '0a6c2948-d4c5-4f21-8128-dc92edefc185' found 0 messages in 33 ms.",3.0.14916.0,2020-12-13T22:27:13.1470348Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 5,,,,,Microsoft.Azure.WebJobs.Script.WebHost.FileMonitoringService,"","Stopping file watchers.",3.0.14916.0,2020-12-13T22:27:13.1471164Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 5,,,ProcessDoc,BackoffDelay,Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener,"","Function 'ProcessDoc' will wait 100 ms before polling queue 'processing'.",3.0.14916.0,2020-12-13T22:27:13.1601317Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 5,,,,,Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher,"","Waiting for RpcFunctionInvocationDispatcher to shutdown",3.0.14916.0,2020-12-13T22:27:13.1662912Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 5,,,,,Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher,"","Draining invocations from language worker channel completed. Shutting down 'RpcFunctionInvocationDispatcher'",3.0.14916.0,2020-12-13T22:27:13.2051132Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 4,,,,,Microsoft.Azure.WebJobs.Hosting.JobHostService,"","Stopping JobHost",3.0.14916.0,2020-12-13T22:27:13.2306154Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'testdocs','message':'Stopping JobHost','category':'Microsoft.Azure.WebJobs.Hosting.JobHostService','hostVersion':'3.0.14916.0','hostInstanceId':'87117e4d-c9b0-484a-ac52-e72bd1533ee5','level':'Information','levelId':2,'processId':10540}",TESTDOCS,,13/12/2020 22:27:13
MS_FUNCTION_LOGS 4,,,ProcessDoc,,Host.Startup,"","Stopping the listener 'Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener' for function 'ProcessDoc'",3.0.14916.0,2020-12-13T22:27:13.2741072Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 5,,,ProcessDoc,GetMessages,Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener,"","Poll for function 'ProcessDoc' on queue 'processing' with ClientRequestId 'e5c78298-fb4c-4a04-93a6-aa586f1edb09' found 0 messages in 33 ms.",3.0.14916.0,2020-12-13T22:27:13.2911513Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'testdocs','message':'Stopping the listener Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener for function ProcessDoc','category':'Host.Startup','hostVersion':'3.0.14916.0','functionName':'ProcessDoc','hostInstanceId':'87117e4d-c9b0-484a-ac52-e72bd1533ee5','level':'Information','levelId':2,'processId':10540}",TESTDOCS,,13/12/2020 22:27:13
MS_FUNCTION_LOGS 5,,,ProcessDoc,BackoffDelay,Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener,"","Function 'ProcessDoc' will wait 213.2767 ms before polling queue 'processing'.",3.0.14916.0,2020-12-13T22:27:13.3219959Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 4,,,ProcessDoc,,Host.Startup,"","Stopped the listener 'Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener' for function 'ProcessDoc'",3.0.14916.0,2020-12-13T22:27:13.3580239Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'testdocs','message':'Stopped the listener Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener for function ProcessDoc','category':'Host.Startup','hostVersion':'3.0.14916.0','functionName':'ProcessDoc','hostInstanceId':'87117e4d-c9b0-484a-ac52-e72bd1533ee5','level':'Information','levelId':2,'processId':10540}",TESTDOCS,,13/12/2020 22:27:13
MS_FUNCTION_LOGS 4,,,,,Host.Startup,"","Job host stopped",3.0.14916.0,2020-12-13T22:27:13.4054177Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'testdocs','message':'Job host stopped','category':'Host.Startup','hostVersion':'3.0.14916.0','hostInstanceId':'87117e4d-c9b0-484a-ac52-e72bd1533ee5','level':'Information','levelId':2,'processId':10540}",TESTDOCS,,13/12/2020 22:27:13
MS_FUNCTION_LOGS 5,,,,,Host.Startup,"","Disposing ScriptHost.",3.0.14916.0,2020-12-13T22:27:13.4561237Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 5,,,,,Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher,"","Disposing FunctionDispatcher",3.0.14916.0,2020-12-13T22:27:13.4716797Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_LOGS 5,,,,,Microsoft.Azure.WebJobs.Script.Workers.Rpc.JobHostRpcWorkerChannelManager,"","Disposing language worker channel with id:00e19496-0b52-4429-87fa-47f2e8579d1d",3.0.14916.0,2020-12-13T22:27:13.4965327Z,,"",,87117e4d-c9b0-484a-ac52-e72bd1533ee5,,TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,functionmetadataprovider.readfunctionsmetadata.readfunctionmetadata.c:\dev\github\queue-functions\python\triggerprocessing,0,0,0,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,scripthostmanager.start.latency,2497,2497,2497,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,functionmetadataprovider.readfunctionsmetadata.readfunctionmetadata.c:\dev\github\queue-functions\python\.venv,0,0,0,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs.buildworkerproviderdictionary.addprovider.c:\program files\microsoft\azure functions core tools\workers\node,45,0,75,3,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,functionmetadataprovider.readfunctionsmetadata.readfunctionmetadata.c:\dev\github\queue-functions\python\processdoc,3,3,3,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,functionmetadataprovider.readfunctionsmetadata.readfunctionmetadata.c:\dev\github\queue-functions\python\downloads,0,0,0,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,functionmetadataprovider.readfunctionsmetadata.readfunctionmetadata.c:\dev\github\queue-functions\python\.vscode,0,0,0,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs.buildworkerproviderdictionary.addprovider.c:\program files\microsoft\azure functions core tools\workers\powershell,58,1,92,3,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,hostjsonfileconfigurationsource.loadhostconfigurationsource.initializehostconfig,0,0,0,2,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,hostjsonfileconfigurationsource.loadhostconfigurationsource.loadhostconfig,0,0,0,2,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,host.startup.outofproc.pythonworker.initialize.attempt0.latency,851,851,851,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,host.startup.latency,639,639,639,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs,260,15,411,3,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,host.startup.runtime.language.python-3.8,0,0,0,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs.buildworkerproviderdictionary.addprovider.c:\program files\microsoft\azure functions core tools\workers\python,49,1,84,3,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,hostjsonfileconfigurationsource.loadhostconfigurationsource,0,0,0,2,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,workerprocess.start,18,18,18,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs.buildworkerproviderdictionary.addprovider.c:\program files\microsoft\azure functions core tools\workers\java,70,10,109,3,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,scripthostmanager.startscripthost.latency,1570,1570,1570,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,scripthostmanager.buildscripthost.latency,348,348,348,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,scriptstartuptypelocator.parseextensions,4,4,4,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,functionmetadataprovider.readfunctionsmetadata,5,5,5,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,functionmetadataprovider.readfunctionsmetadata.readfunctionmetadata.c:\dev\github\queue-functions\python\utils,0,0,0,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,host.startup.getfunctiondescriptors.latency,46,46,46,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"{'IsStopwatchHighResolution:' True}",TESTDOCS,,,,
MS_FUNCTION_METRICS ,,,host.applicationinsights.disabled,0,0,0,1,3.0.14916.0,2020-12-13T22:27:13.5651531Z,"",TESTDOCS,,,,
```

Note that the "CONTAINER_NAME" is set to "testdocs"

This happens something like 5 times in a row before it stops and the host couldn't start.

### Contents of the requirements.txt file

```
azure-core==1.9.0
azure-storage-blob==12.6.0
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
cryptography==3.3.1
idna==2.10
isodate==0.6.0
lxml==4.6.2
msrest==0.6.19
oauthlib==3.1.0
pycparser==2.20
requests==2.25.0
requests-oauthlib==1.3.0
six==1.15.0
urllib3==1.26.2
```

### Related information

local.settings.json
```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "QueueConnectionString": "DefaultEndpointsProtocol=https;AccountName=katiastorage;AccountKey=TQejr8UxBlu4Y4h/vTuJU6RrXHFEdImTCn6JmhcFyIToztbdAvvnX5t6Xg68k/s3KR0oRCEWac/lzO3NfPoKBA==;EndpointSuffix=core.windows.net",
    "CONTAINER_NAME": "testdocs"
  }
}
```

function.json
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "msg",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "processing",
      "connection": "QueueConnectionString"
    }
  ]
}
```

**Comment by balag0** [comment] 2020-12-14 01:43
CONTAINER_NAME is one of the env. variables used by functions runtime to resolve the hosting environment (Dev machine vs Azure vs Core Tools vs Kubernetes)
Setting this variable will cause functions runtime to mis-identify  and lead to incorrect behavior. Closing this as by design.

**Closed by balag0** 2020-12-14 01:43 UTC
Labels: needs-triage (functions)

**Comment by rhl2401** [comment] 2022-11-21 13:11
> CONTAINER_NAME is one of the env. variables used by functions runtime to resolve the hosting environment (Dev machine vs Azure vs Core Tools vs Kubernetes) Setting this variable will cause functions runtime to mis-identify and lead to incorrect behavior. Closing this as by design.
@balag0 

Is there any chance you will publish a list of reserved environment variable names or possibly throw an error when running a function if such variable is used? When using Application Insights, no error is thrown except `The listener for function 'Functions.<functionName>' was unable to start.` which does not reveal anything about this error.
