### ISSUE TITLE
Eventhub event metadata is None

### ISSUE THREAD

**Issue by joal42** [Azure/azure-functions-python-worker#418] opened 2019-05-14 18:16 UTC
I followed the example code in Eventhub triggerred Azure function in python. However, I got `None` for event enqueue time, offset, and etc.
```
import logging
import azure.functions as func

def main(event: func.EventHubEvent):
    logging.info('Function triggered to process a message: ', event.get_body())
    logging.info('  EnqueuedTimeUtc =', event.enqueued_time)
    logging.info('  SequenceNumber =', event.sequence_number)
    logging.info('  Offset =', event.offset)
```
EnqueuedTimeUtc, SequenceNumber, Offset are all `None`.
`event.getbody()` return the right payload I sent to evetnhub. Do I need to modify the payload I sent to eventhub to get the EnqueuedTimeUtc and other metadata?

**Comment by asavaritayal** [comment] 2019-05-15 15:16
@elprans can you investigate this?

**Comment by joal42** [comment] 2019-06-13 18:26
@elprans I tried to set `   "cardinality": "many"` and one. Both of them print offset `None`. Cloud you help with it? Do I need to modify the data I send to eventhub for using those metadata?

**Comment by maiqbal11** [comment] 2019-10-23 18:27
I was able to repro. Will need to take a fix for this in the library code.

**Comment by m-chau** [comment] 2020-01-07 06:39
Still experiencing None for metadata here too... Is this going to be fixed soon?

**Comment by Hazhzeng** [comment] 2020-01-30 18:48
Yes, I can reproduce this issue from my local devbox.
This is due to the iothub- metadata has been moved into a sub-metadata **SystemProperties** of function's trigger, which results in the parser is not working correctly.
https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/eventhub.py#L134

**Comment by Hazhzeng** [comment] 2020-01-31 18:30
Changed Schema, critical data are now been placed into **SystemProperties**
```
{'humidity': string: "72.57455387435327"
, 'Properties': json: "{}"
, 'temperature': string: "21.83708586131132"
, 'SystemProperties': json: "{\"iothub-connection-device-id\":\"MyTestDevice\",\"iothub-connection-auth-method\":\"{\\\"scope\\\":\\\"device\\\",\\\"type\\\":\\\"sas\\\",\\\"issuer\\\":\\\"iothub\\\",\\\"acceptingIpFilterRule\\\":null}\",\"iothub-connection-auth-generation-id\":\"637159305435635051\",\"iothub-enqueuedtime\":\"2020-01-31T18:25:22.094Z\",\"iothub-message-source\":\"Telemetry\",\"x-opt-sequence-number\":200,\"x-opt-offset\":\"85032\",\"x-opt-enqueued-time\":\"2020-01-31T18:25:22.089Z\",\"SequenceNumber\":200,\"Offset\":\"85032\",\"PartitionKey\":null,\"EnqueuedTimeUtc\":\"2020-01-31T18:25:22.089Z\"}"
, 'PartitionContext': json: "{\"CancellationToken\":{\"IsCancellationRequested\":false,\"CanBeCanceled\":true,\"WaitHandle\":{\"Handle\":{\"value\":3328},\"SafeWaitHandle\":{\"IsInvalid\":false,\"IsClosed\":false}}},\"ConsumerGroupName\":\"$Default\",\"EventHubPath\":\"hazeng-iothub-linux\",\"PartitionId\":\"2\",\"Owner\":\"e7219243-1209-41dc-89a8-5ecb474c2537\",\"RuntimeInformation\":{\"PartitionId\":\"2\",\"LastSequenceNumber\":0,\"LastEnqueuedTimeUtc\":\"0001-01-01T00:00:00\",\"LastEnqueuedOffset\":null,\"RetrievalTime\":\"0001-01-01T00:00:00\"}}"
, 'Offset': string: "85032"
, 'EnqueuedTimeUtc': json: "\"2020-01-31T18:25:22.089Z\""
, 'SequenceNumber': json: "200"
, 'sys': json: "{\"MethodName\":\"IotHubOne\",\"UtcNow\":\"2020-01-31T18:25:22.6855069Z\",\"RandGuid\":\"4e133ce3-3b52-4700-8e14-6324a7e459bf\"}"
}
```

**Closed** 2020-02-10 18:21 UTC
Labels: bug, func-stack: Python

**Comment by richardleeaus** [comment] 2020-03-25 07:07
This still appears to be an issue? Nothing within the passed in object `func.EventHubEvent` has **SystemProperties**? Like above, no EnqueuedTime available

**Comment by damnedOperator** [comment] 2020-04-01 06:42
Have the same problem mentioned by @richardleeaus

**Comment by richardleeaus** [comment] 2020-04-01 08:51
Any thoughts @Hazhzeng ?

**Comment by liepertt** [comment] 2020-06-03 11:17
While the `func.EventHubEvent.iothub_metadata` is filled locally with `func host start` where I use 
```
Azure Functions Core Tools (2.7.2508 Commit hash: 4da36643c32783a832094318afcd679fa9d76455)
Function Runtime Version: 2.0.13351.0
```

In the cloud infrastructure it is empty. So when will it be fixed in the cloud. It is currently a show stopper for a project I am working on. Or is there another method to get the sending *device_id* from the event variable I haven't found yet. Any help is appreciated.
