### ISSUE TITLE
Setup devops to publish to PyPI

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#404] opened 2019-04-30 16:47 UTC
- Enable publishing python worker and python library to PyPI via devops
- Investigate providing similar setup for partner teams who need to publish  extensions packages to PyPI

**Comment by asavaritayal** [comment] 2019-05-01 17:07
Closing as a duplicate of https://github.com/Azure/azure-functions-python-worker/issues/141

**Closed by asavaritayal** 2019-05-01 17:07 UTC
Labels: engineering
