### ISSUE TITLE
ModuleNotFoundError when using DevOps Pipeline Task AzureFunctionApp@1

### ISSUE THREAD

**Issue by Fl4v** [Azure/azure-functions-python-worker#708] opened 2020-06-29 12:43 UTC
### Investigative information

When deploying my function from a DevOps pipeline, using the **AzureFunctionApp@1** task, the python worker is unable to find the correct modules.

As a default, the above tasks will upload your `.zip` function code to the Function's storage account, and the following App Setting added: **WEBSITE_RUN_FROM_PACKAGE**, where the value is the path to the blob item.

I have tried troubleshooting this error as described by this [page](https://docs.microsoft.com/en-us/azure/azure-functions/recover-module-not-found?tabs=manual). The documentation indicates that when having troubles with python modules, the following should be added to the application's settings: **SCM_DO_BUILD_DURING_DEPLOYMENT** and **ENABLE_ORYX_BUILD**.

However, when using **WEBSITE_RUN_FROM_PACKAGE**, which is the default behavior of **AzureFunctionApp@1**, **SCM_DO_BUILD_DURING_DEPLOYMENT** is actually ignored. This is documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package).

### Repro steps

Using the DevOps Pipeline builder, build your pipeline following the UI. At the end of the process, you should have a pipeline that should look similar to the below. Alternatively, you can use this [template ](https://github.com/microsoft/azure-pipelines-yaml/blob/master/templates/python-functionapp-to-linux-on-azure.yml) from Microsoft as a guideline.

```yml
trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '{{some_subscription}}'

  # Function app name
  functionAppName: '{{some_function}}'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/functions'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
        fi
      workingDirectory: $(workingDirectory)
      displayName: 'Build extensions'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7 # Functions V2 supports Python 3.6 as of today

    - bash: |
        python -m venv worker_venv
        source worker_venv/bin/activate
        pip install -r requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```

### Expected behavior

I expect that my function will find and install all the python libraries stored in the `requirements.txt` file in the project directory during or after deployment.

### Actual behavior

Python worker is unable to find any modules that my function needs.

### Known workarounds

Deploy your function using the VSCode Function extension.

### Contents of the requirements.txt file:

```txt
azure-functions==1.2.1
azure-storage-blob==12.3.1
flake8==3.8.1
beautifulsoup4==4.9.1
pytest==5.4.2
sendgrid==6.3.1
```

**Comment by priyaananthasankar** [comment] 2020-07-02 19:18
Can you try this?:

Instead of `pip install -r requirements.txt` try recommendation from here `pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt`

https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops?tabs=python

**Comment by Fl4v** [comment] 2020-07-13 09:27
Sorry for the delay in my response. The `pip install --target` seemed to have worked, thanks.

**Comment by dirkesquire** [comment] 2021-01-22 16:26
> Can you try this?:
> 
> Instead of `pip install -r requirements.txt` try recommendation from here `pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt`
> 
> https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops?tabs=python

Another option - should the above script therefore not be `python -m venv .python_packages` instead of `python -m venv worker_venv` then?

Apart from installing the packages, which works absolutely fine, and I can see them installing, I can't seem to see what controls what folder name the Azure Function looks for the virtual environment folder. So is .python_packages hardcoded as the folder that the Azure Function is lookings for?

**Comment by stefanushinardi** [comment] 2021-01-27 00:13
Issue seems to be resolved. Closing the issue

**Closed by stefanushinardi** 2021-01-27 00:13 UTC
Labels: needs-triage (functions)

**Comment by aressler38** [comment] 2021-02-23 19:44
Another important note is that despite all these changes, I still had this problem. The issue in my case was the App Service Plan was a Y1/Dynamic plan, which doesn't support kudu extensions. I had to upgrade the App Service Plan to a S1/Standard app service. After that, with all the above changes, it worked.

**Comment by sujit420421** [comment] 2023-07-20 12:33
@Fl4v @dirkesquire @priyaananthasankar @stefanushinardi can anyone of you help here:
https://stackoverflow.com/questions/76726316/azure-pipeline-cannot-find-installed-python-libraries

I am stuck at this step and need some help.

**Comment by dirkesquire** [comment] 2023-07-20 13:49
> @Fl4v @dirkesquire @priyaananthasankar @stefanushinardi can anyone of you help here: https://stackoverflow.com/questions/76726316/azure-pipeline-cannot-find-installed-python-libraries
> 
> I am stuck at this step and need some help.

Sure thing! I've got this working successfully and importing pandas.
I had to put quite a lot of extra parameters to pip install to get this to work.
Here is a snippet from my **azure_pipelines.yml**:

```
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.9'
      inputs:
        versionSpec: 3.9

    - bash: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt --use-pep517
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'
```
      
**requirements.txt:**
```
wheel
azure-functions
openpyxl
pandas
```

**Comment by sujit420421** [comment] 2023-07-20 14:15
@dirkesquire 
I am downloading the artifact in my local machine and then activating the venv. I am unable to import any library which was installed during build stage. Also, I would like to know whether we can really work this way, I mean archive and build the artifact. then Download it and use like a normal project?

**Comment by dirkesquire** [comment] 2023-07-20 14:47
You might be able to work this way - but bear in mind that you will need to activate and treat '.python_packages' as your virtual directory NOT '.venv'. Azure Functions seems hardcoded to expect that folder name, and will ignore any custom virtual env we create. So therefore any package we install into '.venv' won't work.

**Comment by sujit420421** [comment] 2023-07-21 17:19
@dirkesquire Thanks for your help. The problem is solved. Issue was the mismatch in vmimage and its version.
