### ISSUE TITLE
libgomp.so.1 error

### ISSUE THREAD

**Issue by mathyingzhou** [Azure/azure-functions-python-worker#514] opened 2019-08-12 06:51 UTC
Can not import library `lightgbm`.
#### Investigative information

Please provide the following:

- Timestamp:2019-08-12T06:42:41.172606204Z
- Function App name: http://predictcrimeinboston.azurewebsites.net
- Function name(s) (as appropriate): hello_world
- Core Tools version: 

#### Repro steps

Provide the steps required to reproduce the problem:

Run the app

#### Expected behavior
The app should run

#### Actual behavior

It doesn't run.

#### Known workarounds

No

#### Related information 

`requirements.txt`:
```txt
numpy
pandas
pymongo[srv]
requests
scikit-learn
bs4
holidays
lightgbm
```

**Comment by maiqbal11** [comment] 2019-10-23 17:36
@ahmelsayed, looks to be another case we are missing some system dependencies. `libgomp1` in this case.

**Comment by ahmelsayed** [comment] 2019-10-23 20:07
Yes, looks like it. 

It would help to have a code repro of the issue.

**Comment by horihiro** [comment] 2019-11-02 08:23
If this is a case of `libgomp1`, this is same as https://github.com/Azure/azure-functions-python-worker/issues/493

**Comment by dougfoo** [comment] 2019-11-02 21:32
I have the same issue
It's as simple as importing azureml.train
automl and you'll see this in your python web app which what I see.

**Comment by horihiro** [comment] 2019-11-03 04:45
I confirmed that importing `lightgbm`( `xgboost` and `azureml.train.automl` also) is succeeded by including `libgomp.so.1` into a deployment package, loading it before the importing as following in python code and deploying with `--build-native`.

**\_\_init\_\_.py**
```py:
import ctypes
ctypes.CDLL('/PATH/TO/libgomp.so.1')

import lightgbm
import xgboost
from azureml.train.automl import AutoMLConfig
```

**Note:
All I confirmed are just importing those pip packages, without executing any those methods**, because I'm not a python expert.

----

Just FYI:
In order to get native libraries (i.e. `libgomp.so.1`), I used my repository with some editing.
https://github.com/horihiro/azure-functions-python-opencv-example

**./utils/additional_packages.txt**:
```
libgomp1
```
**./utils/necessary_libraries.txt**:
```
libgomp.so.1
```

**Comment by anirudhgarg** [comment] 2020-01-22 18:32
We have added support for the missing library libgomp.so.1 now.  @mathyingzhou @dougfoo  can you please confirm that it is working for you know.

**Comment by anirudhgarg** [comment] 2020-01-27 04:17
Closing this out as we have added the missing system dependency and xgboost and lightgbm both are loading fine now. Please report if things are not working.

**Closed by anirudhgarg** 2020-01-27 04:17 UTC
Labels: needs-author feedback, system-deps
