### ISSUE TITLE
ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by stefanlenoach** [Azure/azure-functions-python-worker#626] opened 2020-03-04 22:13 UTC
I'm trying to run a web scraper via an Azure Function. When I run the function locally, it works no problem. But when I deploy the function to Azure I encounter a couple of ModuleNotFoundError Exceptions even though I've included both files in requirements.txt. I saw some other people ran into this issue, I tried the solutions in these posts but haven't got anything to work. 

#### Investigative information

- Function App name: scrapertest1
- Function name(s) (as appropriate): ScraperTest
- Core Tools version: 2.7.2254

#### Repro steps

Provide the steps required to reproduce the problem:

I use `func azure functionapp publish scrapertest1 --build remote` to deploy the app and monitor it from the live metrics stream.

#### Expected behavior

I expect the function to see the 'azure' and 'bs4' modules that work fine when I run the function locally.

#### Actual behavior

The function is deployed successfully but whenever my function tries to run it fails due to ModuleNotFoundError exceptions.

#### Known workarounds

I tried several different ways of deploying the function, all unsuccessful in getting around the issue:
`func azure functionapp publish scrapertest1 --build remote`
`func azure functionapp publish scrapertest1`
`func azure functionapp publish scrapertest1 --build-native-deps --force`

#### Contents of the requirements.txt file:
```
appdirs==1.4.3
azure
beautifulsoup4==4.8.2
bs4==0.0.1
certifi==2019.11.28
cfgv==3.0.0
chardet==3.0.4
distlib==0.3.0
filelock==3.0.12
identify==1.4.11
idna==2.8
importlib-metadata==1.5.0
lxml==4.5.0
nodeenv==1.3.5
pre-commit==2.1.0
PyYAML==5.3
requests==2.22.0
selenium==3.141.0
six==1.14.0
soupsieve==1.9.5
toml==0.10.0
urllib3==1.25.8
zipp==3.0.0
azure-storage-file-datalake
```

**Comment by anirudhgarg** [comment] 2020-03-04 22:18
Can you please try including the module **azure-functions** in your requirements.txt and then try

**Comment by stefanlenoach** [comment] 2020-03-04 22:42
Hi Anirudh, thanks for getting back to me so quickly. I added azure-functions to my requirements file but I'm still seeing the same problem.

**Comment by Hazhzeng** [comment] 2020-03-04 23:49
Hi @stefanlenoach,

I fail to reproduce the issue, could you send me the **import statement** where you use the azure module? Thanks.

**Comment by stefanlenoach** [comment] 2020-03-05 00:14
`from azure.storage.filedatalake import DataLakeServiceClient`
and also
`import bs4` (for the bs4 import error)

**Comment by anirudhgarg** [comment] 2020-03-05 00:34
Another question do you need the "azure" module ? https://pypi.org/project/azure/ I believe it is a wrapper around other modules. While we investigate this can you try to remove it and try to include the specific azure service modules that you are using,

**Comment by Hazhzeng** [comment] 2020-03-05 00:51
Hi @stefanlenoach,

I tried to run a sample project with dependencies in your requirements.txt  locally. However, I'm receiving this cross reference issue DataLakeServiceClient -> azure.storage.blob.BlobClient. This is likely due to the latest `azure` library is not compatible with the latest `azure-storage-file-datalake` library (package versions are not pinned in the requirements.txt). 

```
  File "C:\Users\hazeng\Projects\Functions\PythonAzureModule\HttpTrigger\__init__.py", line 7, in <module>
    from azure.storage.filedatalake import DataLakeServiceClient
  File "C:\Users\hazeng\Projects\Functions\PythonAzureModule\.venv37\lib\site-packages\azure\storage\filedatalake\__init__.py", line 7, in <module>
    from ._data_lake_file_client import DataLakeFileClient
  File "C:\Users\hazeng\Projects\Functions\PythonAzureModule\.venv37\lib\site-packages\azure\storage\filedatalake\_data_lake_file_client.py", line 12, in <module>
    from ._path_client import PathClient
  File "C:\Users\hazeng\Projects\Functions\PythonAzureModule\.venv37\lib\site-packages\azure\storage\filedatalake\_path_client.py", line 15, in <module>
    from azure.storage.blob import BlobClient
```

On your local machine, when you setup your virtual environment, you may have different package versions then now. Could you share me with your local machine's **pip freeze** and **the stack trace of the import error**? Thanks again for reporting this issue to us and the collaboration.

**Comment by stefanlenoach** [comment] 2020-03-05 02:41
@Hazhzeng of course! Here's the result of pip freeze:
```
adal==1.2.2
appdirs==1.4.3
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-common==1.1.24
azure-core==1.2.2
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-datalake-store==0.0.48
azure-eventgrid==1.3.0
azure-graphrbac==0.40.0
azure-keyvault==1.1.0
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.1.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.6.2
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.4.1
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.6.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.7.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.2.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
azure-storage==0.36.0
azure-storage-blob==12.2.0
azure-storage-common==1.4.2
azure-storage-file==1.4.0
azure-storage-file-datalake==12.0.0b7
azure-storage-queue==1.4.0
beautifulsoup4==4.8.2
bs4==0.0.1
certifi==2019.11.28
cffi==1.14.0
cfgv==3.0.0
chardet==3.0.4
cryptography==2.8
distlib==0.3.0
filelock==3.0.12
identify==1.4.11
idna==2.8
importlib-metadata==1.5.0
isodate==0.6.0
lxml==4.5.0
msrest==0.6.11
msrestazure==0.6.2
nodeenv==1.3.5
oauthlib==3.1.0
pre-commit==2.1.0
pycparser==2.20
PyJWT==1.7.1
python-dateutil==2.8.1
PyYAML==5.3
requests==2.22.0
requests-oauthlib==1.3.0
selenium==3.141.0
six==1.14.0
soupsieve==1.9.5
toml==0.10.0
urllib3==1.25.8
virtualenv==20.0.8
zipp==3.0.0
```
Is there someway I can get a more detailed stacktrace for deployed azure functions? From the Live Metric Stream all I get is this:
```
Time
6:38:05 PM
Message
ModuleNotFoundError: No module named 'azure'
ProcessId
30
HostInstanceId
04bf92b2-a32e-4e73-9d7a-42a1d5aa74f5
prop__{OriginalFormat}
ModuleNotFoundError: No module named 'azure'
```

**Comment by gaurcs** [comment] 2020-03-05 17:09
I am getting the same error but with the "requests" module. I am using the [pipeline](https://github.com/microsoft/azure-pipelines-yaml/blob/master/templates/python-functionapp-to-linux-on-azure.yml) suggested by Microsft. Everything works in the local but the Applications Metrics logs are showing otherwise.

**Comment by stefanlenoach** [comment] 2020-03-05 17:21
@anirudhgarg I tried doing as you suggested, the ModuleNotFoundError Exceptions persist

**Comment by gaurcs** [comment] 2020-03-05 17:28
@stefanlenoach are you deploying from local/Azure CLI or using the Azure Pipelines? I tried both ways and getting the same error. The only time I didn't get the error was when I was actually doing the pip install command as part of my release deploy but that beats the point of doing the "build"

**Comment by stefanlenoach** [comment] 2020-03-05 17:30
@gaurcs I've been using the Azure CLI

**Comment by Hazhzeng** [comment] 2020-03-05 19:56
Hi @stefanlenoach,

The **azure** module is not compatible with the azure-storage package. You can see this in the PyPI page https://pypi.org/project/azure/ `This package is not compatible with azure-storage`

The **azure-storage-file-datalake** module you use has a dependency on **azure-storage-blob**, it will be installed while deployment, which breaks the parent **azure** module.
```python
    install_requires=[
        "azure-core<2.0.0,>=1.2.2",
        "msrest>=0.6.10",
        "azure-storage-blob~=12.0"
    ]
```

Please consider removing the **azure** module and manually pick the packages you need in your requirements.txt.

**Comment by gaurcs** [comment] 2020-03-05 20:06
@Hazhzeng All my packages are in requirements.txt. I am still getting the same error.

**Comment by anirudhgarg** [comment] 2020-03-05 20:33
@gaurcs - your issue could be different. Can you please open a different issue and please include your requirements.txt in that issue

**Comment by stefanlenoach** [comment] 2020-03-06 04:24
@Hazhzeng I tried doing as you say, I still see the azure and bs4 import Excetptions. 
Here's the requirements.txt I used:
```
appdirs==1.4.3
beautifulsoup4==4.8.2
bs4==0.0.1
certifi==2019.11.28
cfgv==3.0.0
chardet==3.0.4
distlib==0.3.0
filelock==3.0.12
identify==1.4.11
idna==2.8
importlib-metadata==1.5.0
lxml==4.5.0
nodeenv==1.3.5
pre-commit==2.1.0
PyYAML==5.3
requests==2.22.0
selenium==3.141.0
six==1.14.0
soupsieve==1.9.5
toml==0.10.0
urllib3==1.25.8
zipp==3.0.0
azure-core==1.2.2
azure-storage-blob==12.2.0
azure-storage-file-datalake==12.0.0b7
```

**Comment by anirudhgarg** [comment] 2020-03-06 05:41
And this is still working fine locally ?

**Comment by stefanlenoach** [comment] 2020-03-06 17:13
yes

**Comment by gaurcs** [comment] 2020-03-09 14:29
@stefanlenoach were you able to solve this issue?

**Comment by stefanlenoach** [comment] 2020-03-09 14:44
@gaurcs nope, I'm trying to figure out a workaround...what about yourself?

**Comment by gaurcs** [comment] 2020-03-09 14:58
For me, there is a lot of confusion in docs about "How to deploy a Python Function in Linux Consumption Plan". The docs are various in nature and tells a different story. From what I see, I am [running from a deployment package ](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package). What it does is build everything and mounts it to /home/site/wwwroot/ folder. So what you gotta do is pack everything before you publish like this 

`pip3.7 install --target $(System.DefaultWorkingDirectory)/.python_packages/lib/site-packages -r requirements.txt`

That got resolved but I am using the template. Can you share your cli commands to publish?

**Comment by stefanlenoach** [comment] 2020-03-09 15:18
I've been using the Azure CLI and have tried these 3 commands all with the same, result:
`func azure functionapp publish test1 --build remote`
`func azure functionapp publish test1`
`func azure functionapp publish test1 --build-native-deps --force`

**Comment by anirudhgarg** [comment] 2020-03-09 17:26
Sorry about the confusion in docs around publishing - we will try to make it cleaner @kulkarnisonia16  for feedback around this. 

For deployment of a Python app to the Consumption app you can use the following ways: 
1). Using func cli (Not this is not what we call the Azure CLI that is the az command) - this is what @stefanlenoach seems to be using. This is documented here: 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#publishing-to-azure

2). Using az command (Azure CLI) 

3). Using VSCode (which uses func CLI i.e. 1). internally)

4). Using GitHub Actions/Azure Devops - they use a mix of API's etc. internally. 

Next is the story around modules:
1). You can either just reference the names of your modules in a requirements.txt file and do a remote build (also the default) and the platform will pip install the modules on your behalf. This is documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#remote-build

2). Modules that you want to install on your own you can add to the site-packages folder. This is documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#custom-dependencies

@stefanlenoach - if you are local environment is working and it fails when you are in Azure - can you try to use a python venv (virtual environment) when running locally. This will then replicate your environment when running in Azure. We think what might be happening is that you have some module references that are resolving locally because of how the local paths are set up.

**Comment by stefanlenoach** [comment] 2020-03-09 17:45
@anirudhgarg thanks for the detailed response. I've been using a virtual environment the whole time and tested the issue you suggested by deleting my current venv and creating a new one with a fresh installation of my requirements.txt. This import error persists after I did this, yet it runs fine locally. This morning I decided to remove the functionality pertaining to azure uploading which was the piece that required the Azure import. As I mentioned before I was having another import issue with bs4 (Beautiful Soup) and have been trying to focus on this import alone. I just tried deploying via custom dependencies and yet I'm _still_ running into the same ModuleNotFoundError for bs4. 
Specifically I ran:
`pip install  --target="<PROJECT_DIR>/.python_packages/lib/site-packages"  -r requirements.txt`
then
`func azure functionapp publish <APP_NAME> --no-build`

**Comment by stefanlenoach** [comment] 2020-03-09 18:31
@anirudhgarg I think I might have figured out the issue. Seems like the problem might have been related to the way I was calling my Python script from the __init__.py file. I'm importing the file like this now (as it says so in the docs): 
`from . import my_file` whereas before I was using the subprocess module. This seems to fix the issue for the bs4 package import error, I'll see now if it resolves the other Azure import error

**Comment by gaurcs** [comment] 2020-03-10 13:41
#627 @stefanlenoach I solved my issue. See my comment.

**Closed** 2020-03-10 17:13 UTC
Labels: needs-attention :wave:
