### ISSUE TITLE
Failed to start language worker for: python.

### ISSUE THREAD

**Issue by fernandrez** [Azure/azure-functions-python-worker#229] opened 2018-10-29 15:18 UTC
I followed the steps in [AzureFunctions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local) to create a Python Function but when I tried to run it with ```func start``` I got:
```
func host start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.1.748 Commit hash: 5db20665cf0c11bedaffc96d81c9baef7456acb3)
Function Runtime Version: 2.0.12134.0
[29/10/2018 15:09:16] Building host: startup suppressed:False, configuration suppressed: False
[29/10/2018 15:09:17] Reading host configuration file 'C:\path_to_folder\Deployer\host.json'
[29/10/2018 15:09:17] Host configuration file read:
[29/10/2018 15:09:17] {
[29/10/2018 15:09:17]   "version": "2.0"
[29/10/2018 15:09:17] }
[29/10/2018 15:09:17] Initializing Host.
[29/10/2018 15:09:17] Host initialization: ConsecutiveErrors=0, StartupCount=1
[29/10/2018 15:09:17] Starting JobHost
[29/10/2018 15:09:17] Starting Host (HostId=ar2301649w1-60652735, InstanceId=b4c81e61-f576-4449-a431-1487e1f41694, Version=2.0.12134.0, ProcessId=10000, AppDomainId=1, Debug=False, FunctionsExtensionVersion=)
[29/10/2018 15:09:17] Loading functions metadata
[29/10/2018 15:09:17] 1 functions loaded
[29/10/2018 15:09:17] Starting language worker process:python  "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 50346 --workerId e4a7da1b-b54c-4536-bbfc-333ff416d8a2 --requestId 4205ee23-e11d-409c-a957-6269517084df --grpcMaxMessageLength 134217728
[29/10/2018 15:09:17] python process with Id=19760 started
[29/10/2018 15:09:17] Generating 1 job function(s)
[29/10/2018 15:09:17] Found the following functions:
[29/10/2018 15:09:17] Host.Functions.ARM
[29/10/2018 15:09:17]
[29/10/2018 15:09:17] Host initialized (359ms)
[29/10/2018 15:09:17] Host started (369ms)
[29/10/2018 15:09:17] Job host started
Hosting environment: Production
Content root path: C:\path_to_folder\Deployer
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...

Http Functions:

        ARM: [GET,POST] http://localhost:7071/api/ARM

[29/10/2018 15:09:22] Host lock lease acquired by instance ID '0000000000000000000000001960BDE6'.
[29/10/2018 15:09:23] Traceback (most recent call last):
[29/10/2018 15:09:23]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[29/10/2018 15:09:23] Traceback (most recent call last):
[29/10/2018 15:09:23]     args.grpc_max_msg_len)
[29/10/2018 15:09:23]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 36, in <module>
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[29/10/2018 15:09:23]     main()
[29/10/2018 15:09:23]     host, port, worker_id, request_id, grpc_max_msg_len))
[29/10/2018 15:09:23]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[29/10/2018 15:09:23]     args.grpc_max_msg_len)
[29/10/2018 15:09:23]     return loop.run_until_complete(main)
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[29/10/2018 15:09:23]   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\asyncio\base_events.py", line 468, in run_until_complete
[29/10/2018 15:09:23]     host, port, worker_id, request_id, grpc_max_msg_len))
[29/10/2018 15:09:23]     return future.result()
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[29/10/2018 15:09:23]     return loop.run_until_complete(main)
[29/10/2018 15:09:23]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[29/10/2018 15:09:23]   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\asyncio\base_events.py", line 468, in run_until_complete
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[29/10/2018 15:09:23]     return future.result()
[29/10/2018 15:09:23]     await disp._grpc_connected_fut
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\dispatcher.py", line 337, in __poll_grpc
[29/10/2018 15:09:23]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[29/10/2018 15:09:23]     timeout=self._grpc_connect_timeout)
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\grpc\_utilities.py", line 134, in result
[29/10/2018 15:09:23]     await disp._grpc_connected_fut
[29/10/2018 15:09:23]     self._block(timeout)
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\dispatcher.py", line 337, in __poll_grpc
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\grpc\_utilities.py", line 84, in _block
[29/10/2018 15:09:23]     timeout=self._grpc_connect_timeout)
[29/10/2018 15:09:23]     raise grpc.FutureTimeoutError()
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\grpc\_utilities.py", line 134, in result
[29/10/2018 15:09:23] Language Worker Process exited.
[29/10/2018 15:09:23]     self._block(timeout)
[29/10/2018 15:09:23] python exited with code 1
 .
[29/10/2018 15:09:23]   File "C:\path_to_folder\env\lib\site-packages\grpc\_utilities.py", line 84, in _block
[29/10/2018 15:09:23] grpc.FutureTimeoutError
[29/10/2018 15:09:23]     raise grpc.FutureTimeoutError()
[29/10/2018 15:09:23] grpc.FutureTimeoutError
[29/10/2018 15:09:23] Starting language worker process:python  "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 50346 --workerId 6464dbe9-3adb-4651-8ac3-09be99767c45 --requestId a233668f-18f0-4934-83b3-767c77c1eb4d --grpcMaxMessageLength 134217728
[29/10/2018 15:09:23] python process with Id=19488 started
[29/10/2018 15:09:29] Traceback (most recent call last):
[29/10/2018 15:09:29]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[29/10/2018 15:09:29]     args.grpc_max_msg_len)
[29/10/2018 15:09:29] Traceback (most recent call last):
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[29/10/2018 15:09:29]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 36, in <module>[29/10/2018 15:09:29]     host, port, worker_id, request_id, grpc_max_msg_len))

[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[29/10/2018 15:09:29]     main()
[29/10/2018 15:09:29]     return loop.run_until_complete(main)
[29/10/2018 15:09:29]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[29/10/2018 15:09:29]   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\asyncio\base_events.py", line 468, in run_until_complete
[29/10/2018 15:09:29]     args.grpc_max_msg_len)
[29/10/2018 15:09:29]     return future.result()
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[29/10/2018 15:09:29]     host, port, worker_id, request_id, grpc_max_msg_len))
[29/10/2018 15:09:29]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[29/10/2018 15:09:29]     return loop.run_until_complete(main)
[29/10/2018 15:09:29]     await disp._grpc_connected_fut
[29/10/2018 15:09:29]   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\asyncio\base_events.py", line 468, in run_until_complete
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\dispatcher.py", line 337, in __poll_grpc
[29/10/2018 15:09:29]     return future.result()
[29/10/2018 15:09:29]     timeout=self._grpc_connect_timeout)
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[29/10/2018 15:09:29]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
**[29/10/2018 15:09:29] Language Worker Process exited.**
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
**[29/10/2018 15:09:29] python exited with code 1**
 .
[29/10/2018 15:09:29]     await disp._grpc_connected_fut
[29/10/2018 15:09:29]   File "C:\path_to_folder\env\lib\site-packages\grpc\_utilities.py", line 134, in result
[29/10/2018 15:09:29] Starting language worker process:python  "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 50346 --workerId 2a2fb8fd-91d4-4f1d-910f-654aa1a980ac --requestId 146c3297-4087-4bd1-b63f-c479aa2f1be9 --grpcMaxMessageLength 134217728
[29/10/2018 15:09:29] python process with Id=8496 started
```

#### Investigative information

Please provide the following:

- 29/10/2018 15:09:29
- Function App name Deployer
- Function name(s) (as appropriate): ARM

#### Repro steps

Provide the steps required to reproduce the problem:

1. Follow the steps in [AzureFunctions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local) under Windows
2. Run the function with ```func host start / func start```

#### Expected behavior

Provide a description of the expected behavior.

 - The Endpoint should start working and processing requests

#### Actual behavior

Provide a description of the actual behavior observed.

 - The error mentioned in the description
 - When trying to make a request I get this:
```
Executed 'Functions.ARM' (Failed, Id=f5dbce67-f3a9-4ca6-b558-8eddcfd83a6d)
[29/10/2018 15:14:15] System.Private.CoreLib: Exception while executing function: Functions.ARM. System.Private.CoreLib: Failed to start language worker for: python. One or more errors occurred. (python exited with code 1
 ) (python exited with code 1
 ) (python exited with code 1
 ). python exited with code 1
 .
[29/10/2018 15:14:15] Executed HTTP request: {
[29/10/2018 15:14:15]   "requestId": "74d31ed0-a540-4970-bf32-1a3b73c23814",
[29/10/2018 15:14:15]   "method": "POST",
[29/10/2018 15:14:15]   "uri": "/api/ARM",
[29/10/2018 15:14:15]   "identities": [
[29/10/2018 15:14:15]     {
[29/10/2018 15:14:15]       "type": "WebJobsAuthLevel",
[29/10/2018 15:14:15]       "level": "Admin"
[29/10/2018 15:14:15]     }
[29/10/2018 15:14:15]   ],
[29/10/2018 15:14:15]   "status": 500,
[29/10/2018 15:14:15]   "duration": 1104
[29/10/2018 15:14:15] }
```

**Comment by maiqbal11** [comment] 2018-10-29 16:51
Looks like the Python language worker is unable to establish communication with the Functions host to be able to process messages. However, I am unable to repro given the instructions that you've shared. Is this the first function that you are running or have you previously run functions (in other languages) on your machine?

**Comment by fernandrez** [comment] 2018-10-29 18:51
I was able to run the C# example, but as soon as I include ```using Microsoft.IdentityModel.Clients.ActiveDirectory;``` it stops working; I mean the function is not indexed, and I am not being able to register the extensions, because the documentation [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#local-development-azure-functions-core-tools) is not really clear for me. I do try to follow them but they do not seem to work.

**Comment by fernandrez** [comment] 2018-10-29 18:53
Actually even on the portal "IDE" I get:
```
[Error] run.csx(5,17): error CS0234: The type or namespace name 'IdentityModel' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
```

**Comment by maiqbal11** [comment] 2018-10-29 19:42
For referencing external assemblies, you would need to first include the NuGet package. 

To accomplish this in the Portal IDE, you can use the following instructions: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#using-nuget-packages. Note that all v2 functions run on .NET Core, so would need to include the appropriate tags in the *project.json* to target .NET Core.

**Comment by fernandrez** [comment] 2018-10-29 20:17
thank you @maiqbal11. Apparently the *project.json* approach does not work anymore, and we have to do it with the **function.proj** approach. It just worked for me including this content in the **function.proj** file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="4.3.0"/>
  </ItemGroup>
</Project>
```

**Comment by maiqbal11** [comment] 2018-10-29 20:31
Glad that you were able to get unblocked. We'll work on getting documentation up to date. 

Are you still facing the original issue you had with Python?

**Comment by fernandrez** [comment] 2018-10-29 20:59
I am @maiqbal11. To deliver something by EOD today I went the C# way using the portal as my IDE. Though I am definitely commited to get the Python local development environment working during the week. What do you think I am missing? What can I do to prevent the Python worker from timing out? Appreciate your time and availability.

**Comment by maiqbal11** [comment] 2018-10-29 21:11
It's hard to say exactly as each person's development environment may have slight variations that can cause issues. I see that you're using Python installed through Visual Studio. You could try re-installing and using Python 3.6 from here: https://www.python.org/downloads/release/python-367/. I've encountered some issues (not necessarily Functions related) when trying to use the Python that Visual Studio provides. Feel free to post about any new/same errors you get when you make the switch and we can dig some more.

**Comment by fernandrez** [comment] 2018-10-29 21:37
alright will install Python 3.6 from scratch, and will avoid using the Python installed trhough VS.
Will come back with the results.

**Comment by maiqbal11** [comment] 2018-11-02 15:39
@fernandrez, were you able to get the function working?

**Comment by maiqbal11** [comment] 2018-11-05 15:50
Closing as I believe this issue is resolved (judging by the thumbs on my earlier comment). Please feel free to comment if this is not the case.

**Closed by maiqbal11** 2018-11-05 15:50 UTC

**Comment by fernandrez** [comment] 2018-11-07 19:03
Sorry for the delay, only today was I able to try this. And I keep getting the same error even using a newly installed Python 3.6.7 from the link

**Comment by fernandrez** [comment] 2018-11-07 19:17
`C:\path_to_folder\Deply>func start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.1.748 Commit hash: 5db20665cf0c11bedaffc96d81c9baef7456acb3)
Function Runtime Version: 2.0.12134.0
[7/11/2018 19:14:21] Building host: startup suppressed:False, configuration suppressed: False
[7/11/2018 19:14:21] Reading host configuration file 'C:\path_to_folder\Deply\host.json'
[7/11/2018 19:14:21] Host configuration file read:
[7/11/2018 19:14:21] {
[7/11/2018 19:14:21]   "version": "2.0"
[7/11/2018 19:14:21] }
[7/11/2018 19:14:21] Initializing Host.
[7/11/2018 19:14:21] Host initialization: ConsecutiveErrors=0, StartupCount=1
[7/11/2018 19:14:21] Starting JobHost
[7/11/2018 19:14:21] Starting Host (HostId=ar2301649w1-1537521372, InstanceId=473eecfa-5d4f-4288-9840-6a108673d3f7, Version=2.0.12134.0, ProcessId=2972, AppDomainId=1, Debug=False, FunctionsExtensionVersion=)
[7/11/2018 19:14:21] Loading functions metadata
[7/11/2018 19:14:21] 1 functions loaded
[7/11/2018 19:14:21] Starting language worker process:python  "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 64767 --workerId c0fb4661-12c7-4756-b402-655ba03fcb66 --requestId e162f8d3-c423-4252-9265-184dd9680bf6 --grpcMaxMessageLength 134217728
[7/11/2018 19:14:21] python process with Id=7860 started
[7/11/2018 19:14:21] Generating 1 job function(s)
[7/11/2018 19:14:22] Found the following functions:
[7/11/2018 19:14:22] Host.Functions.TimeseriesForecast
[7/11/2018 19:14:22]
[7/11/2018 19:14:22] Host initialized (313ms)
[7/11/2018 19:14:22] Host started (326ms)
[7/11/2018 19:14:22] Job host started
Hosting environment: Production
Content root path: C:\path_to_folder\Deply
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...

Http Functions:

        TimeseriesForecast: [GET,POST] http://localhost:7071/api/TimeseriesForecast

[7/11/2018 19:14:27] Host lock lease acquired by instance ID '000000000000000000000000CD9A81E8'.
[7/11/2018 19:14:27] Traceback (most recent call last):
[7/11/2018 19:14:27]   File "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[7/11/2018 19:14:27] Traceback (most recent call last):
[7/11/2018 19:14:27]     args.grpc_max_msg_len)
[7/11/2018 19:14:27]   File "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 36, in <module>
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[7/11/2018 19:14:27]     main()
[7/11/2018 19:14:27]     host, port, worker_id, request_id, grpc_max_msg_len))
[7/11/2018 19:14:27]   File "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[7/11/2018 19:14:27]     args.grpc_max_msg_len)
[7/11/2018 19:14:27]     return loop.run_until_complete(main)
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[7/11/2018 19:14:27]   File "C:\Users\myuser\AppData\Local\Programs\Python\Python36\Lib\asyncio\base_events.py", line 473, in run_until_complete
[7/11/2018 19:14:27]     host, port, worker_id, request_id, grpc_max_msg_len))
[7/11/2018 19:14:27]     return future.result()
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[7/11/2018 19:14:27]     return loop.run_until_complete(main)
[7/11/2018 19:14:27]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[7/11/2018 19:14:27]   File "C:\Users\myuser\AppData\Local\Programs\Python\Python36\Lib\asyncio\base_events.py", line 473, in run_until_complete
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[7/11/2018 19:14:27]     return future.result()
[7/11/2018 19:14:27]     await disp._grpc_connected_fut
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\dispatcher.py", line 337, in __poll_grpc
[7/11/2018 19:14:27]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[7/11/2018 19:14:27]     timeout=self._grpc_connect_timeout)
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\grpc\_utilities.py", line 134, in result
[7/11/2018 19:14:27]     await disp._grpc_connected_fut
[7/11/2018 19:14:27]     self._block(timeout)[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\dispatcher.py", line 337, in __poll_grpc

[7/11/2018 19:14:27]     timeout=self._grpc_connect_timeout)
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\grpc\_utilities.py", line 84, in _block
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\grpc\_utilities.py", line 134, in result
[7/11/2018 19:14:27]     raise grpc.FutureTimeoutError()
[7/11/2018 19:14:27]     self._block(timeout)
[7/11/2018 19:14:27] grpc.FutureTimeoutError
[7/11/2018 19:14:27]   File "C:\path_to_folder\Deply\lib\site-packages\grpc\_utilities.py", line 84, in _block
[7/11/2018 19:14:27] Language Worker Process exited.
[7/11/2018 19:14:27]     raise grpc.FutureTimeoutError()
[7/11/2018 19:14:27] python exited with code 1
 .
[7/11/2018 19:14:27] grpc.FutureTimeoutError
[7/11/2018 19:14:27] Starting language worker process:python  "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 64767 --workerId 9a96f590-8c24-44c1-839a-df3f53b22380 --requestId 26f06b08-732b-4dc1-bf9f-0c2122a864fc --grpcMaxMessageLength 134217728
[7/11/2018 19:14:27] python process with Id=2268 started
[7/11/2018 19:14:33] Traceback (most recent call last):
[7/11/2018 19:14:33] Traceback (most recent call last):
[7/11/2018 19:14:33]   File "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[7/11/2018 19:14:33]   File "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 36, in <module>
[7/11/2018 19:14:33]     args.grpc_max_msg_len)
[7/11/2018 19:14:33]     main()
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[7/11/2018 19:14:33]   File "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[7/11/2018 19:14:33]     host, port, worker_id, request_id, grpc_max_msg_len))
[7/11/2018 19:14:33]     args.grpc_max_msg_len)
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[7/11/2018 19:14:33]     return loop.run_until_complete(main)
[7/11/2018 19:14:33]     host, port, worker_id, request_id, grpc_max_msg_len))
[7/11/2018 19:14:33]   File "C:\Users\myuser\AppData\Local\Programs\Python\Python36\Lib\asyncio\base_events.py", line 473, in run_until_complete
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[7/11/2018 19:14:33]     return future.result()
[7/11/2018 19:14:33]     return loop.run_until_complete(main)
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[7/11/2018 19:14:33]   File "C:\Users\myuser\AppData\Local\Programs\Python\Python36\Lib\asyncio\base_events.py", line 473, in run_until_complete
[7/11/2018 19:14:33]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[7/11/2018 19:14:33]     return future.result()
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[7/11/2018 19:14:33]     await disp._grpc_connected_fut
[7/11/2018 19:14:33]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\dispatcher.py", line 337, in __poll_grpc[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect

[7/11/2018 19:14:33] Language Worker Process exited.
[7/11/2018 19:14:33]     timeout=self._grpc_connect_timeout)
[7/11/2018 19:14:33] python exited with code 1
 .
[7/11/2018 19:14:33]   File "C:\path_to_folder\Deply\lib\site-packages\grpc\_utilities.py", line 134, in result
[7/11/2018 19:14:33] Starting language worker process:python  "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 64767 --workerId d3a23c67-08e2-4450-81b6-24efd906f0c9 --requestId 19240660-c950-45a9-877f-6cf0bebaa2a5 --grpcMaxMessageLength 134217728
[7/11/2018 19:14:33]     await disp._grpc_connected_fut
[7/11/2018 19:14:33] python process with Id=6268 started`

**Comment by fernandrez** [comment] 2018-11-07 19:29
This is my local.settings.json:

`{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
	"AzureWebJobsStorage": "UseDevelopmentStorage=true"
  }
}`

**Comment by fernandrez** [comment] 2018-12-11 22:02
come on please guys please, I implore you!

**Comment by priyaananthasankar** [comment] 2018-12-13 00:44
Can you try an actual storage? If you are looking for a time series forecast check out this sample: https://github.com/priyaananthasankar/parseltongue/tree/master/PyFunctionsOnACI/ForecastingApp

**Comment by marshallford** [comment] 2019-01-10 16:38
I am also running into this issue. Ubuntu 18.04 WSL. Default timer trigger.

**Comment by QaiserAli** [comment] 2019-01-20 19:40
I am also runnning the same issue as described above. Any idea how to fix this?

**Comment by sptramer** [comment] 2019-01-22 17:38
I've figured out the issue: It's related to a socket configuration problem on WSL. See https://github.com/Microsoft/WSL/issues/1419 and https://github.com/grpc/grpc/issues/16998

**Comment by fernandrez** [comment] 2019-01-22 20:24
Thank you @sptramer, have you found out any workaround to make this work under windows?

**Comment by sptramer** [comment] 2019-01-22 20:50
Unfortunately not, because the socket issue is in WSL itself. There may be a later version of GRPC that works, but I haven't investigated in depth.

**Comment by lightenup** [comment] 2019-01-23 12:18
I've had a similar issue on linux, which was caused by a corporate proxy. I needed to set no_proxy environment variable for localhost/127.0.0.1

**Comment by holwech** [comment] 2019-02-13 09:57
For those who find this via Google and working on Windows, as mentioned above, the fix is simply to set the environmental variable `NO_PROXY=localhost,127.0.0.1`. The error probably occurs because you are working behind a corporate proxy and have the variables `HTTP_PROXY` and `HTTPS_PROXY` set, but not `NO_PROXY`. This is an issue with gRPC, see https://github.com/grpc/grpc/issues/9989.

**Comment by danielcarletti** [comment] 2019-03-26 17:17
I had this problem and @lightenup/@holwech fixes solved it. I am begin a corporate proxy and have the variables set. I just set NO_PROXY and my function works fine now.

**Comment by AGARWAS8** [comment] 2021-04-01 13:25
> For those who find this via Google and working on Windows, as mentioned above, the fix is simply to set the environmental variable `NO_PROXY=localhost,127.0.0.1`. The error probably occurs because you are working behind a corporate proxy and have the variables `HTTP_PROXY` and `HTTPS_PROXY` set, but not `NO_PROXY`. This is an issue with gRPC, see [grpc/grpc#9989](https://github.com/grpc/grpc/issues/9989).

@holwech I tried your solution. The issue was resolved but reappeared a day after. I have tried removing and adding the setting again. Have tried using a new virtual environment as well but no success. Can you help?
