### ISSUE TITLE
BYOC BYOF documentation and portal issues

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#138] opened 2018-06-01 16:22 UTC
Bring Your Own Container (BYOC) 
This scenario is completely broken for Azure as of last week. You can run everything locally, but actually referencing a Docker image in Azure does not work. Debugging is very difficult and is not well documented.
It is super confusing to determine which base image should be used (latest, v2.0.11651-alpha, 2.0.0-jessie, dev-nightly). They reference multiple different images in their tools and some versions are unstable. 
The Azure portal Functions App selection is very confusing between Linux and Docker options, because both allow you to specify the docker container (2 screenshots): 

 
I find that between these two docs, it is unclear how they map to what is being created through the Azure Portal: 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli-linux (This appears to create a Docker functions App) 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image (This appears to create a Linux functions App) 

Debugging experience in Azure is very poor, the logs in the above screenshot are not complete (Maybe they cut off after a certain number of lines?) 

(minor) The UI that allows you to set the container image is buggy, after you set it sometimes you see the old image name and have to refresh. 

(minor) It is recommend to store secrets in the Application Settings, but all of the secret values are visible in the Portal in plaintext.

**Comment by asavaritayal** [comment] 2018-06-04 09:26
Breaking this down - 

>Bring Your Own Container (BYOC)
>This scenario is completely broken for Azure as of last week. You can run everything locally, but actually referencing a Docker image in Azure does not work. Debugging is very difficult and is not well documented.

This is caused due to a runtime regression - https://github.com/Azure/azure-functions-host/pull/2917. Fix here - https://github.com/Azure/azure-functions-docker-python-sample/pull/18#pullrequestreview-125492965 

>It is super confusing to determine which base image should be used (latest, v2.0.11651-alpha, 2.0.0-jessie, dev-nightly). They reference multiple different images in their tools and some versions are unstable.

Please do not use any builds that are not documented. 

> The Azure portal Functions App selection is very confusing between Linux and Docker options, because both allow you to specify the docker container (2 screenshots):
> I find that between these two docs, it is unclear how they map to what is being created through the Azure Portal:
> https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli-linux (This appears to create a Docker functions App)
> https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image (This appears to create a Linux functions App)

Link 1 is bring-your-own-files. Link 2 is bring-your-custom-image. The docker option in BYOF is a feature of App Service. The option will disappear once  the consumption offering is available. 

> Debugging experience in Azure is very poor, the logs in the above screenshot are not complete (Maybe they cut off after a certain number of lines?)

Can you please attach the screenshot? 

> (minor) The UI that allows you to set the container image is buggy, after you set it sometimes you see the old image name and have to refresh.

@dariagrigoriu , @Jen7714 as this is a Linux issue. 

> (minor) It is recommend to store secrets in the Application Settings, but all of the secret values are visible in the Portal in plaintext.

The Key Vault integration is on the UX backlog for Functions. @mattchenderson

**Comment by asavaritayal** [comment] 2018-06-06 17:47
No action required at this time. @priyaananthasankar RE: the logging issue - 

>Debugging experience in Azure is very poor, the logs in the above screenshot are not complete (Maybe they cut off after a certain number of lines?)

Let us know if you have a screenshot of the logs being cut off so we can investigate further. Closing the current issue for now.

**Closed by asavaritayal** 2018-06-06 17:47 UTC
