### ISSUE TITLE
Functions hangs calling a async method from AML SDK

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#312] opened 2019-02-04 20:24 UTC
Triggering a job in AML SDK uses their async method run.submit which is not supposed to block.
On a standalone script it comes back under 30secs, but when triggered within an Azure function it calls the AML service job and triggers an experiment successfully inside AML service, but does not return back to the function. The function hangs.

We need a way to spawn off a job in AML Service and return with job id. Since the call to the async makes the functions wait, we are unable to achieve this. 

cc: @maiqbal11 @michhar @asavaritayal

**Comment by michhar** [comment] 2019-02-04 20:32
For repro:  we are following steps [here](https://github.com/michhar/deeplearning-aml-and-azure-functions)and the standalone script for testing AzureML only is [here](https://github.com/michhar/deeplearning-aml-and-azure-functions/blob/master/dnn/HttpTrigger/test.py).  @priyaananthasankar Please amend if you have additional notes.  Thanks.

**Comment by jeffhollan** [comment] 2019-03-04 23:58
Hey @maiqbal11 know you have some profiling work - have you had the chance to look at this at all? This sounds like it may take priority over profiling if there is deadlock.

**Comment by maiqbal11** [comment] 2019-03-05 00:00
@jeffhollan, I'll get on this tomorrow with priority. Was working on closing out some packaging issues.

**Comment by maiqbal11** [comment] 2019-03-08 00:14
@michhar, @priyaananthasankar, I was able to find the reason for the function hanging. Looks to be the following line of code in `__init__.py`:

`shutil.copy(os.path.join(os.getcwd(), 'HttpTrigger', 'pytorch_train.py'), project_folder)`

https://github.com/michhar/deeplearning-aml-and-azure-functions/blob/4419a6cdd0ac1289ff88452e29c1a004574ff6b5/dnn/HttpTrigger/__init__.py#L67

When the file `pytorch_train.py` is copied within the function folder, it causes a host restart and contention with the previous host instance that was processing the request. Since `pytorch_train.py` is part of the original function code, it gets indexed and a copy operation triggers the file watcher to restart the host. Commenting out that line of code and creating the `project` folder with the `pytorch_train.py` file already present unblocked `run = experiment.submit(estimator)`. 

I'll circle back with more specific recommendations if the copying behavior is needed but thought that I'd provide an update here.

**Comment by priyaananthasankar** [comment] 2019-03-08 01:23
Thanks @maiqbal11 . This is interesting. Is this specific to Python language worker? Or a host issue? will C# functions have the same issue?
I would suggest to package whatever files needed for training through AzDevOps. Will check with @michhar as well.

**Comment by asavaritayal** [comment] 2019-03-08 18:15
The functionality is imposed by design from the host. The goal is to enable users to edit locally and in the portal without having to manually restart the site each time.

**Comment by jeffhollan** [comment] 2019-03-08 18:22
You can configure this in the `host.json` as well - I would expect here an empty array may mean we don't watch any files

https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#watchdirectories

/cc @mathewc to confirm if you can disable all watching

**Comment by maiqbal11** [comment] 2019-03-11 15:08
Tried using an empty directory but it still restarts when the file is copied. We also don't recommend using the function folder for temporary file storage because of unexpected behavior like this. @priyaananthasankar, aside from using Azure DevOps, it is also possible to use temp directory constructs built directly into Python. The following StackOverflow provides some good insight: https://stackoverflow.com/questions/847850/cross-platform-way-of-getting-temp-directory-in-python.

**Comment by maiqbal11** [comment] 2019-03-11 15:08
Closing this as temporary file behavior should be easily achievable via alternatives.

**Closed by maiqbal11** 2019-03-11 15:08 UTC
Labels: P1, tracked-customer

**Comment by michhar** [comment] 2019-03-22 17:54
@priyaananthasankar @maiqbal11 Thank you for all  of your work.  I've updated the code - there needs to be a permanent folder, `project`, with the training script and related assets for running the experiment with Azure ML (basically it copies the contents of this folder up to a separate compute for the actual training job).  I do know Azure ML creates a folder `aml_config` as well, but this now doesn't seem to be a problem.

If you wish to try now, please do so and provide any further feedback.  Thanks, again.

[repo](https://github.com/michhar/deeplearning-aml-and-azure-functions)
