### ISSUE TITLE
Unable to import python-dateutil in 1.0.0a6, can do so in 1.0.0a4

### ISSUE THREAD

**Issue by monteledwards** [Azure/azure-functions-python-worker#252] opened 2018-12-04 16:45 UTC
requirements.txt 
```
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
grpcio
grpcio-tools
protobuf
requests
python-dateutil
```

A function with an import statement of `from dateutil import parser as date_parser`
throws a "Module not found" error. Switching back to 1.0.0a4 from 1.0.0a6 resolves the issue.

**Comment by asavaritayal** [comment] 2018-12-04 18:57
@ankitkumarr can you please look into this issue?

**Comment by ankitkumarr** [comment] 2018-12-04 19:58
I could not reproduce this issue using the latest version of `azure-functions-core-tools (2.3.148)`.

@monteledwards could you try using the new version of `azure-functions-core-tools` and let me know if you still see the error?

Thanks for reporting!

**Comment by asavaritayal** [comment] 2018-12-04 20:50
Closing issue due to no repro. Please feel free to re-open if you're still running into the error.

**Closed by asavaritayal** 2018-12-04 20:50 UTC
