### ISSUE TITLE
Unable to import pyodbc - even with --build-native-deps

### ISSUE THREAD

**Issue by monteledwards** [Azure/azure-functions-python-worker#249] opened 2018-11-30 21:37 UTC
For the sake of simplicity, i've shortnened function to as follows

```
import logging

import azure.functions as func

import pyodbc

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')

    if name:
        return func.HttpResponse(f"Hello {name}!")
    else:
        return func.HttpResponse(
             "Please pass a name on the query string or in the request body",
             status_code=400
        )
```

I deploy to Azure with `func azure functionapp publish myfunctionapp --build-native-deps --additional-packages "python3-dev libevent-dev unixodbc-dev "`

And I still get issues when trying to execute the function. HTTP responds with 500 and the portal tells me 

> Function (HttpTrigger) Error: Failed to start language worker process for: python. bash exited with code 255 [78] Failed to execute script worker,ImportError: cannot import name 'main'.
> Session Id: 3f21797ce66145edb348ae0836ba794d

In our actual project where this import statement lives in shared code outside of the entry __init__.py file I get the plain "ModuleNotFoundError: No module named 'pyodbc'"

Using function core tools 2.2.70

**Comment by maiqbal11** [comment] 2018-12-01 00:57
Hi @monteledwards, could you share your requirements.txt file?

**Comment by monteledwards** [comment] 2018-12-01 09:30
azure-functions
azure-functions-worker
pyodbc

**Comment by asavaritayal** [comment] 2018-12-01 21:36
@monteledwards what specific versions of azure-functions and azure-functions-worker ?

**Comment by monteledwards** [comment] 2018-12-04 14:00
Hi @asavaritayal 
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6

**Comment by owenwhenry** [comment] 2018-12-05 20:02
Hey,

Chiming in here as I'm also struggling with this problem - I have a daemon (named Cespanar, for you ToB fans out there) that uses pyodbc to try and connect to a database in Azure, do some simple monitoring, and trigger an email to me/other admins when an issue is detected. 

I've been able to get things working locally, but after publishing my function using --build-native-deps I'm seeing another issue. This is the log file from my most recent test run in the portal:

```
2018-12-05T19:12:57.820 [Information] Executing 'Functions.Cespanar_Automated_Monitoring' (Reason='This function was programmatically called via the host APIs.', Id=7eeec5d7-f1e4-4574-9a22-96b3e7b6298f)
2018-12-05T19:12:57.886 [Error] Executed 'Functions.Cespanar_Automated_Monitoring' (Failed, Id=7eeec5d7-f1e4-4574-9a22-96b3e7b6298f)
Result: Failure
Exception: ModuleNotFoundError: No module named 'pyodbc'
Stack:   File "home/site/wwwroot/worker_venv/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 203, in _handle__function_load_request
  File "home/site/wwwroot/worker_venv/lib/python3.6/site-packages/azure/functions_worker/loader.py", line 66, in load_function
  File "root/.pyenv/versions/3.6.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/site/wwwroot/Cespanar_Automated_Monitoring/__init__.py", line 5, in <module>
    import pyodbc
```

I'm wondering if the problem isn't the fact that we're forcing things into a Linux environment which has additional requirements for using pyodbc - check out this section from [their github](https://github.com/mkleehammer/pyodbc/wiki/Install#installing-on-linux):

> Installing on Linux
> When installing pyodbc on Linux, pip will download and compile the pyodbc source code. This requires that some related components and source files be available for the compile to succeed.
> 
> Ubuntu 18.04
> On Ubuntu systems, all you need to do is run
> 
> sudo apt install python3-pip
> sudo apt install unixodbc-dev
> pip3 install --user pyodbc
> Debian Stretch
> Similar to Ubuntu, you need to install unixodbc-dev, but you will also need to install gcc and g++. Note gcc package is automatically installed when installing g++
> 
> apt-get update
> apt-get install g++
> apt-get install unixodbc-dev
> pip install pyodbc
> CentOS 7
> From a clean minimal install of CentOS 7, the following steps were required:
> 
> sudo yum install epel-release
> sudo yum install python-pip gcc-c++ python-devel unixODBC-devel
> pip install --user pyodbc
> Fedora 27
> sudo dnf install redhat-rpm-config gcc-c++ python3-devel unixODBC-devel
> pip3 install --user pyodbc
> OpenSUSE
> Similar to Fedora, the following packages were required after a clean install of OpenSUSE Leap 42.3
> 
> sudo zypper install gcc-c++ python3-devel unixODBC-devel
> pip3 install --user pyodbc

@asavaritayal, this seems like the likely culprit to me, but I haven't done much digging into how Functions are being run in Linux...

**Comment by owenwhenry** [comment] 2018-12-10 16:13
Hey @asavaritayal, did you all have any insights into why pyodbc would be continuing to fail to build? I don't seem to have access to much in the function due to the way it was built out as a package, so I'm not sure if unixodbc-dev is actually getting added to the machine running the function or not.

**Comment by asavaritayal** [comment] 2018-12-11 06:49
I can confirm that `unixodbc-dev` is installed in the Python image. See here - https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/python.Dockerfile#L48

@ankitkumarr can you please investigate this issue?

**Comment by ankitkumarr** [comment] 2018-12-11 19:35
Hi @owenwhenry, I was able to reproduce the issue in the latest version of the core-tools published. I do have a [PR](https://github.com/Azure/azure-functions-core-tools/pull/910/files) out for the cause of this problem. This fix should be part of the next release (most likely this week). 

As a mitigation for now, you can use the flag `--no-bundler`. More information about this flag and our publishing workflow [here](https://aka.ms/func-python-publish). 
Apologies for the inconvenience, and please let me know if you still see issues.

**Comment by owenwhenry** [comment] 2018-12-11 19:42
No apologies necessary @ankitkumarr, especially not after such a prompt response - mostly just glad to have helped you all move Python closer to being fully implemented, since I'm really excited about using it.

Tagging @monteledwards for his benefit as I assume he'll be as interested in this fix as I am.

**Comment by ankitkumarr** [comment] 2018-12-11 19:49
Thanks @owenwhenry, we appreciate all the testing and the bug reports. We still have some ways to go, but are very excited about getting Python functions where it should be.

**Comment by owenwhenry** [comment] 2018-12-11 19:50
@ankitkumarr You're welcome - also enjoying the one line fix. It's always something small isn't it?

**Comment by ankitkumarr** [comment] 2018-12-11 19:58
@owenwhenry, It really is! A little embarrassing of me to not have caught this earlier. But, better late than ever.

**Comment by owenwhenry** [comment] 2018-12-12 15:31
Hey,

I fiddled with this a bit and it (almost) works. While it no longer chokes on loading pyodbc, the construction of the connection string is different for Linux than it is for Windows.

[Here's the official pyodbc documentation](https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Linux-or-Mac). 

[Here's the Microsoft documentation. ](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-2017) 

[Here's a tutorial on it](https://www.progress.com/tutorials/odbc/sql-server-odbc-driver-for-linux-quick-start-guide) (skip down past the bits about the EULA to see how they configure the .ini file for ODBC).

In all cases, it uses a DSN file to set the database parameters rather than calling them as part of the function from within Python. I'm not sure how we would do that in the current way that Functions are published from the Azure CLI. Can we just pass the file as part of the publishing process?

If not, I'm not sure how feasible it is to connect to a database from within a function. I could configure a linux vm that holds the scripts and config files and set the cron there, but it defeats the purpose of trying to use a function app.

**Comment by asavaritayal** [comment] 2018-12-18 21:08
Thanks @owenwhenry. I'm closing the issue since it no longer requires any work from engineering. Appreciate your sharing the script here for others' perusal.

**Closed by asavaritayal** 2018-12-18 21:08 UTC

**Comment by owenwhenry** [comment] 2019-01-08 22:41
@Torwalt Unfortunately not yet, my experience with Linux and CI is somewhat lacking. It's also going around the block to get next door - the entire allure of Functions is that you don't have to set up and configure a machine to run your code, but that's exactly what you have to do in order to get pyodbc to work. 

There's a good chance that Microsoft will eventually implement a Windows VM, though!

**Comment by nkma1989** [comment] 2019-01-11 14:12
Unfortunately I am stuck as the exact same place. Have a solution been found?

**Comment by nkma1989** [comment] 2019-01-15 12:33
@owenwhenry Don't know if it applicable for you, but I ended up using table storage as my data dump.
Works just fine. Here is the package I used:
https://pypi.org/project/azure-cosmosdb-table/

**Comment by carterpy** [comment] 2019-03-25 20:49
I'm like @owenwhenry - I've been making .py files to do little tasks on windows vms and now I'm using python preview linux distro for azure and it's like, where's the odbc drivers? But I'm also greening on Ubuntu on my on-prem rig and just did a bunch of apt-gets to get some mssql drivers. @asavaritayal [says we've got unixodbc](https://github.com/Azure/azure-functions-docker/issues/32). Sooooo, if an Azure Function is really a docker image basically, where can we go to do our [sudo ACCEPT_EULA=Y apt-get install mssql-tools and sudo ACCEPT_EULA=Y apt-get install msodbcsql17](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017)? And since we're in the land of Microosft already can't we ask for mssql tools and msodbcsql17 to just kind of be in the default package distro? Like I get it if somebody is trying to do odbc connections to mongo or neo4j, but if it's microsoft sql server for example, can we have that in the defaults?

**Comment by carterpy** [comment] 2019-03-25 21:01
Watch @asavaritayal be like, [use a custom docker image](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image)

**Comment by konradsitarz** [comment] 2019-06-04 08:16
I encounter the same issue with pyodbc module loading. 
I'm able to run it locally but while deployed it shows the error

```
Result: Failure
Exception: ModuleNotFoundError: No module named 'pyodbc'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 229, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/site/wwwroot/HttpCombineForecast/__init__.py", line 5, in <module>
    from process_flow.process_logic import get_combined_prediction
  File "/home/site/wwwroot/process_flow/process_logic.py", line 7, in <module>
    from process_flow.data_processing import start_data_processing
  File "/home/site/wwwroot/process_flow/data_processing.py", line 2, in <module>
    from exceptions.anormal_forecast_logic import check_for_anomaly
  File "/home/site/wwwroot/exceptions/anormal_forecast_logic.py", line 1, in <module>
    from services.notification_service import notification_exception
  File "/home/site/wwwroot/services/notification_service.py", line 8, in <module>
    from mailer.mailer import Mailer
  File "/home/site/wwwroot/mailer/mailer.py", line 5, in <module>
    from services.configuration_service import get_mailer_configuration
  File "/home/site/wwwroot/services/configuration_service.py", line 1, in <module>
    from tools.database_connection import Database
  File "/home/site/wwwroot/tools/database_connection.py", line 1, in <module>
    import pyodbc
```
Version of pyodbc:
pyodbc==4.0.26

Deployment command, which shows no error: 
`func azure functionapp publish <app> --build-native-deps`

**Comment by abkeble** [comment] 2019-06-08 20:18
@konradsitarz I managed to import pypyodbc successfully as well, however, I received the following error when attempting to connect to an azure sql database:
`Exception: OperationalError: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found")`
Were you able to get around this?

**Comment by konradsitarz** [comment] 2019-06-08 21:52
@abkeble I would try with replacing 
'ODBC Driver **13** for SQL Server'  'with ODBC Driver **17** for SQL Server' in the connection string. I think it's the version of db provided on azure.

**Comment by abkeble** [comment] 2019-06-10 16:36
@konradsitarz That worked, thanks!

**Comment by Tomar-shubham** [comment] 2019-07-27 17:37
@abkeble @konradsitarz how did you manage to import pypyodbc/pyodbc ?

**Comment by abkeble** [comment] 2019-07-29 08:50
@Tomar-shubham I was unable to import pyodbc. I did manage to import pypyodbc by including `pypyodbc` in my requirements.txt file for the project. Then I included the line `import pypyodbc` in my code and used `pypyodbc.connect(CONNECTION_STRING)` to connect to my sql server.

**Comment by shril** [comment] 2019-10-23 06:25
I am trying to use `PyODBC` with `SQLAlchemy`.

```
from sqlalchemy import create_engine
import pypyodbc

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=********************;"
    "DATABASE=******************;"
    "UID=***********;"
    "PWD=*************"
)

engine = create_engine(
    "mssql+pyodbc:///?odbc_connect={}".format(params),
    module=pypyodbc,
    echo=True
)
```

But I am getting this error every-time I make a request to the function-app.

```
Exception while executing function: Functions.create_assessment Result: Failure
Exception: OperationalError: (pypyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired')
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by bsnithin44** [comment] 2019-10-23 07:28
@shril 

```Login timeout expired``` This could probably be due to wrong password and username combination or the IP - firewall settings.

Try to whitelist your IP in the firewall settings of the DB and check

**Comment by answerquest** [comment] 2020-03-12 07:59
Hi @shril , @bsnithin44 , I uninstalled pyodbc package and kept only pypyodbc in the python environment and ran the sqlalchemy code. But that results in error saying that pyodbc module is missing. I then changed the "mssql+pyodbc:///" in connection string to "mssql+pypyodbc:///" and that results in a `NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mssql.pypyodbc` error.

I don't think sqlalchemy supports pypyodbc :(

**Comment by resolvo** [comment] 2020-05-29 20:20
I'm able to deploy everything and when I use the driver= '{ODBC Driver 17 for SQL Server}' I'm receiving this error : ODBC SQL type -155 is not yet supported.

Hopeto find a solution :)

**Comment by jigar-patel1** [comment] 2022-01-06 03:20
I'm facing similar issue where we are using Python in Azure Function App in Linux OS to deploy update on Managed Instance with below connection settings and getting an error _**[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')**_

`conn = pyodbc.connect("DRIVER={ODBC Driver 17 for SQL Server};SERVER=<ManagedInstance>;PORT=<PORT>;database=<DATABASE_NAME>;UID=<SQLUSER>;PWD=<PASSWORD>")`

It works fine in Visual Studio while testing but once deployed to app it fails to work.

**Comment by nickpeterson** [comment] 2022-08-16 00:49
Has anyone ran into this issue when deploying using Azure Pipelines? When I deploy directly from Visual Studio Code I have no issues. When I deploy using Azure Pipelines ,  the build stage has no issues downloading and successfully installing pyodbc and the deploy works as well. However my HTTP function fails immediately when triggered with "ModuleNotFoundError: No module named 'pyodbc'".  Any help on this would be awesome !

**Comment by christina13181** [comment] 2022-09-19 21:23
@nickpeterson I have the same issue. Have you solved it? Thanks

**Comment by nickpeterson** [comment] 2022-09-21 13:31
@christina13181 

> @nickpeterson I have the same issue. Have you solved it? Thanks

I ended up having to change the pip install syntax on the bash step from

`- bash: |
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
        workingDirectory: $(workingDirectory)`

to 
`- bash: |
        pip install --target="$(System.DefaultWorkingDirectory)/.python_packages/lib/site-packages" -r requirements.txt`

**Comment by DireWolfCoder** [comment] 2025-02-05 06:05
Is this still a thing in 2025? Pyodbc works great locally but in azure it is not found even though it is in my requirements.txt file. tried both python 3.10 and 3.11. ODBC 17 and 18. What's up??
