### ISSUE TITLE
502 Bad Gateway on Python Azure Function

### ISSUE THREAD

**Issue by gerwin3** [Azure/azure-functions-python-worker#384] opened 2019-04-11 15:46 UTC
I have a small python Azure Function that intermittently fails with a 502 Bad Gateway response. Usually it works a few times and then stops working, sometimes it starts working again. Everything is fine locally BTW.

I attached Application Insights to get some logs, but only the logs of successful runs are there. It seems like the request never even hits my Azure Function at all. The 502 Bad Gateway errors do no only occur when calling the function, but they actually show up when I go to the configure page in the Azure Portal itself from time to time. (Would like to attach a screenshot but it's working as of now. Will do so when it starts failing again.)

The only thing I can find is an exception occurring when the host starts: `HostInitializationException` "Did not find functions with language [python]." Luckily, the host auto-restarts and the second time is successfully starts. Not sure if this is related to the issue at all.

Sadly I cannot attach the source file but I'm pretty sure that it is not related to my code anyway.

#### Investigative information

- Timestamp: Has a 25% chance of happening; Usually in batches that last a few hours.
- Runtime version: 2.0.12333.0 (~2)

**Comment by gerwin3** [comment] 2019-04-16 08:43
A screenshot of the error in Azure portal:

![image](https://user-images.githubusercontent.com/1304177/56195026-67599200-6034-11e9-80fe-5230e4b31c03.png)

**Comment by touhonoob** [comment] 2019-04-17 09:33
Same here

**Comment by maiqbal11** [comment] 2019-04-17 17:38
Would you be able to share the name of your function app? We can look at the logging on our side to figure out what's going on.

**Comment by gerwin3** [comment] 2019-04-17 19:24
I cannot publicly unfortunately. Can I contact you some other way?

**Comment by touhonoob** [comment] 2019-04-17 23:28
@maiqbal11 https://akv-functions-python.azurewebsites.net/api/create-test-transaction

deployed with 

```
func azure functionapp publish akv-functions-python --publish-local-settings --build-native-deps
```

**Comment by maiqbal11** [comment] 2019-04-18 19:49
@gerwin3, can you include a log line like the following from your function execution:

"Executed 'Functions.HttpTrigger' (Succeeded, Id=ef8b4f0c-2615-479a-afe9-e5ba7a03cedb)"

You can execute the function from Portal to see these logs. Using Application Insights would be more reliable since Portal logging can be inconsistent. Could you also provide the time stamp during which the function execution happened? This information should allow us to locate the function.

**Comment by gerwin3** [comment] 2019-04-19 10:17
@maiqbal11 It failed twice with a 502 but on the third try I got a successful execution at 2019-04-19 10:08:09.853 UTC (Note that a 500 Internal Server error is returned but that's OK because I used a dummy argument value). The log in Azure shows the ID so you should be able to find it.

Again, the failed attempt does not show up in the logs at all.

Thanks for your help!

**Comment by maiqbal11** [comment] 2019-04-19 17:54
Hi @gerwin3, we'll need the log with the ID line to be provided from your end. Given just the timestamp, we would not be able to find the function logs for your app given all the other functions executing during that time. 

Here are full instructions on how you can configure Application Insights for your function app to retrieve the information (since Portal log streaming experience is not ironed out for Python):

1. Configure Application Insights via Portal by going to your Function App. You should see the following banner at the top if App Insights is not already configured:

![ConfigureAppInsights](https://user-images.githubusercontent.com/42051041/56436548-11cdf100-6291-11e9-96f0-80fb65563bbc.PNG)

2. Navigate to your App Insights instance and click on the "Search" option on the left:

![AppInsightsTab](https://user-images.githubusercontent.com/42051041/56436600-42ae2600-6291-11e9-989c-af67b32969f5.PNG)

3. Execute the function and wait about ~10 mins to see the logs populated in Search. Share the line with the (Succeeded, Id = XXXXXXX) as shown below:

![ExecutionLogs](https://user-images.githubusercontent.com/42051041/56436641-696c5c80-6291-11e9-975e-e0b25a52e0e9.PNG)

**Comment by gerwin3** [comment] 2019-04-19 18:43
@maiqbal11 Ah, I misunderstood. This is the ID: b5924b90-677f-4954-ad1c-7c9381320bff

**Comment by brettcannon** [comment] 2019-06-24 20:50
I got 3 recent 502s for my GitHub bot function and I'm fairly certain it's not my code as I was able to resend the webhook requests from GitHub and everything worked (the bot is stateless so shouldn't be affected by side-effects).
```
Content-Length: 1477
Content-Type: text/html
Date: Thu, 20 Jun 2019 21:05:44 GMT
Server: Microsoft-IIS/10.0


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>
 </fieldset></div>
</div>
</body>
</html>
```

**Comment by asavaritayal** [comment] 2019-07-11 20:51
@Hazhzeng @maiqbal11 this seems to be the 502 on coldstart fix that @balag0 fixed last week. Could you please confirm?

**Comment by Hazhzeng** [comment] 2019-07-11 21:10
Yes, the issue should be fixed in the new update. The update is currently deploying. We can check if the issue is fixed.

**Comment by shanjin14** [comment] 2019-07-28 12:28
> Yes, the issue should be fixed in the new update. The update is currently deploying. We can check if the issue is fixed afterwards.

Hi Hazhzeng, any update on this ?Thanks Hazhzeng!

**Comment by Hazhzeng** [comment] 2019-07-29 15:29
> > Yes, the issue should be fixed in the new update. The update is currently deploying. We can check if the issue is fixed afterwards.
> 
> Hi Hazhzeng, any update on this ?Thanks Hazhzeng!

The the new update for Linux Consumption Python has been deployed to East Asia, we are currently rolling out to other regions.

**Comment by jhop310** [comment] 2019-07-30 12:27
Any ETA on when we can expect this fix rolled out to all regions?

**Comment by anirudhgarg** [comment] 2019-09-27 21:19
This fix has been rolled out to all regions. Please open if you see it again.

**Closed by anirudhgarg** 2019-09-27 21:19 UTC
Labels: func-stack: Python

**Comment by bszewczyk** [comment] 2019-12-04 11:51
I'm getting same error now. Is there something going wrong again?

**Comment by anirudhgarg** [comment] 2019-12-04 23:33
Can you conform what your app name, region is ?

**Comment by bszewczyk** [comment] 2019-12-05 06:10
app name: aml-test-ml-functions
region: west europe

**Comment by balag0** [comment] 2019-12-05 07:51
The 502 failures are due to 2 reasons
https://docs.microsoft.com/en-us/windows/win32/wininet/wininet-errors

1) ERROR_INTERNET_TIMEOUT
12002
The request has timed out.

2) ERROR_HTTP_INVALID_SERVER_RESPONSE
12152
The server response could not be parsed.

12002 failures are due to the request taking > 230 seconds (more information and workarounds available here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout )

Could there be some specific (invalid) response back from the failing function causing the 12152 errors in certain scenarios?

**Comment by bszewczyk** [comment] 2019-12-05 10:17
Hi, I figure out that could be time out so I changed my code and it works faster. I just expected another error message if my function timed out. When I look to the Monitor I see that everything went ok. 

Even though now I'm struggling with second error.

Is there any limit of size of result from function? Only one thing that came in my mind is that there is to long content.

**Comment by balag0** [comment] 2019-12-06 00:47
Yes. Reducing the over all latency should help with 12002 errors.

Regarding the 12152 errors, I think it would be helpful to see if the failures correlate to some response content length. Do you have an approx range of the response length the function is returning? I will see if i can repro the failure on one of my apps.

**Comment by bszewczyk** [comment] 2019-12-06 09:36
This is my result for example

 {"result": [0.0, 0.0, 2.16, 0.0, 0.0, 0.0, 0.0, 1.03, 2.13, 1.04, 0.0, 0.0, 2.08, 0.0, 0.0, 0.0, 0.0, 0.04, 2.16, 0.0, 4.27, 3.15, 2.12, 0.0, 0.0, 2.12, 0.97, 0.0, 0.0, 0.0, 0.0, 0.02, 2.1, 2.13, 0.97, 4.29, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05, 0.0, 2.19, 2.09, 0.0, 0.0, 2.17, 0.01, 0.0, 0.0, 0.0, 0.0, 1.02, 0.0, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06, 0.03, 2.13, 2.12, 3.21, 0.0, 0.0, 0.03, 0.0, 2.16, 0.0, 2.08, 9.83, 0.0, 0.0, 0.0, 0.0, 0.0, 0.96, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 2.12, 1.05, 0.0, 0.01, 0.0, 2.09, 4.28, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.03, 0.0, 3.24, 2.07, 3.18, 0.0, 0.0, 0.01, 1.01, 2.13, 0.0, 3.19, 0.0, 0.0, 0.0, 0.0, 3.17, 3.16, 4.26, 2.04, 0.0, 0.0, 0.0, 0.0, 2.04, 0.0, 0.0, 0.0, 0.0, 0.0, 1.01, 0.0, 0.0, 0.0, 0.0, 0.04, 0.0, 1.06, 0.0, 5.41, 0.0, 0.0, 0.0, 1.07, 0.0, 3.18, 5.38, 3.16, 0.0, 0.0, 0.0, 2.1, 0.0, 0.0, 0.0, 3.25, 0.0, 13.08, 0.0, 0.0, 0.0, 2.01, 2.08, 0.0, 0.0, 0.0, 3.14, 0.0, 4.29, 0.0, 0.0, 0.0, 0.0, 0.0, 3.16, 0.98, 0.0, 0.0, 3.22, 0.0, 0.0, 0.0, 0.0, 1.06, 0.0, 4.32, 4.3, 2.01, 0.0, 4.23, 1.0, 0.0, 2.04, 4.25, 2.01, 4.19, 0.0, 0.0, 0.0, 0.0, 2.01, 2.01, 5.3, 0.0, 0.0, 0.0, 0.0, 3.19, 2.02, 4.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.93, 4.24, 0.0, 2.12, 0.0, 0.0, 2.08, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08, 0.0, 0.0, 1.06, 0.02, 0.0, 1.06, 4.29, 3.16, 0.0, 2.13, 0.0, 0.99, 1.0, 0.0, 0.95, 0.98, 0.0, 0.01, 2.1, 4.29, 0.0, 0.0, 1.02, 3.22, 0.0, 0.0, 2.05, 0.0, 4.24, 0.0, 0.0, 0.0, 0.0, 1.02, 0.0, 3.16, 0.0, 0.0, 0.0, 0.0, 0.0, 4.26, 0.96, 2.07, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03, 0.0, 2.1, 0.0, 0.0, 0.0, 0.0, 0.04, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.06, 5.46, 2.15, 2.06, 0.0, 0.0, 0.0, 0.02, 0.0, 0.0, 4.32, 5.38, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.13, 0.0, 0.01, 2.15, 1.04, 0.0, 0.0, 0.0, 0.0, 0.02, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.06, 0.0, 0.0, 0.0, 3.23, 1.09, 0.0, 0.02, 0.0, 0.0, 1.01, 0.0, 0.0, 0.0, 0.04, 0.0, 3.27, 0.0, 0.0, 1.07, 0.0, 0.03, 1.05, 0.0, 0.0, 0.0, 0.0, 0.01, 0.06, 1.06, 0.0, 0.0, 4.31, 0.0, 0.0, 0.02, 0.0, 0.0, 2.1, 0.0, 0.0, 0.0, 0.03, 0.0, 4.35, 0.0, 3.17, 2.37, 2.4, 2.1, 3.08, 3.01, 3.94, 3.99, 4.12, 3.57, 3.19, 4.32, 4.52, 4.77, 5.25, 4.52, 4.88, 4.54, 4.92, 6.0, 6.3, 6.4, 6.17, 6.07, 5.72, 6.38, 6.76, 7.13, 7.75, 7.12, 7.16, 6.85, 7.84, 7.77, 8.7, 8.74, 8.87, 8.33, 7.94, 9.07, 9.27, 9.52, 10.01, 9.27, 9.64, 9.29, 9.67, 10.76, 11.05, 11.15, 10.93, 10.83, 10.48, 11.14, 11.52, 11.89, 12.51, 11.88, 11.92, 11.61, 12.59, 12.52, 13.46, 13.5, 13.63, 13.08, 12.7, 13.83, 14.03, 14.28, 14.76, 14.03, 14.39, 14.05, 14.43, 15.51, 15.81, 15.91, 15.69, 15.59, 15.23, 15.9, 16.27, 16.65, 17.27, 16.64, 16.67, 16.37, 17.35, 17.28, 18.21, 18.26, 18.39, 17.84, 17.46, 18.59, 18.79, 19.04, 19.52, 18.79, 19.15, 18.81, 19.19, 20.27, 20.57, 20.67, 20.44, 20.34, 19.99, 20.65, 21.03, 21.41, 22.02, 21.39, 21.43, 21.13, 22.11, 22.04, 22.97, 23.01, 23.14, 22.6, 22.21, 23.35, 23.54, 23.8, 24.28, 23.54, 23.91, 23.56, 23.94, 25.03, 25.32, 25.42, 25.2, 25.1, 24.75, 25.41, 25.79, 26.16, 26.78, 26.15, 26.19, 25.88, 26.86, 26.79, 27.73, 27.77, 27.9, 27.35, 26.97, 28.1, 28.3, 28.55, 29.03, 28.3, 28.66, 28.32, 28.7, 29.78, 30.08, 30.18, 29.96, 29.86, 29.5, 30.17, 30.55, 30.92, 31.54, 30.91, 30.95, 30.64, 31.62, 31.55, 32.48, 32.53, 32.66, 32.11, 31.73, 32.86, 33.06, 33.31, 33.79, 33.06, 33.42, 33.08, 33.46, 34.54, 34.84, 34.94, 34.71, 34.61, 34.26, 34.93, 35.3, 35.68, 36.29, 35.67, 35.7, 35.4, 36.38, 36.31, 37.24, 37.28, 37.41, 36.87, 36.49, 37.62, 37.82, 38.07, 38.55, 37.81, 38.18, 37.83, 38.21, 39.3, 39.59, 39.69, 39.47, 39.37, 39.02, 39.68, 40.06, 40.43, 41.05, 40.42, 40.46, 40.15, 41.13, 41.07, 42.0, 42.04, 42.17, 41.63, 41.24, 42.37, 42.57, 42.82, 43.31, 42.57, 42.94, 42.59, 42.97, 44.06, 44.35, 44.45, 44.23, 44.13, 43.77, 44.44, 44.82, 45.19, 45.81, 45.18, 45.22, 44.91, 45.89, 45.82, 46.75, 46.8, 46.93, 46.38, 46.0, 47.13, 47.33, 47.58, 48.06, 47.33, 47.69, 47.35, 47.73, 48.81, 49.11, 49.21, 48.98, 48.88, 48.53, 49.2, 49.57, 49.95, 50.56, 49.94, 49.97, 49.67, 50.65, 50.58, 51.51, 51.55, 51.68, 51.14, 50.76, 51.89, 52.09, 52.34, 52.82, 52.09, 52.45, 52.1, 52.48, 53.57, 53.86, 53.96, 53.74, 53.64, 53.29, 53.95, 54.33, 54.7, 55.32, 54.69, 54.73, 54.42, 55.4, 55.34, 56.27, 56.31, 56.44, 55.9, 55.51, 56.64, 56.84, 57.09, 57.58, 56.84, 57.21, 56.86, 57.24, 58.33, 58.62, 58.72, 58.5, 58.4, 58.05, 58.71, 59.09, 59.46, 60.08, 59.45, 59.49, 59.18, 60.16, 60.09, 61.03, 61.07, 61.2, 60.65, 60.27, 61.4, 61.6, 61.85, 62.33, 61.6, 61.96, 61.62, 62.0, 63.08, 63.38, 63.48, 63.25, 63.16, 62.8, 63.47, 63.84, 64.22, 64.84, 64.21, 64.24, 63.94, 64.92, 64.85, 65.78, 65.83, 65.96, 65.41, 65.03, 66.16, 66.36, 66.61, 67.09, 66.36, 66.72, 66.38, 66.76, 67.84, 68.14, 68.24, 68.01, 67.91, 67.56, 68.22, 68.6, 68.97, 69.59, 68.96, 69.0, 68.69, 69.68, 69.61, 70.54, 70.58, 70.71, 70.17, 69.78, 70.91, 71.11, 71.37, 71.85]}

I'm returning long arrays.

**Comment by bszewczyk** [comment] 2019-12-09 07:58
I noticed that it falls down when I run a multiple threads. I am using parallel loop to run multiple azure functions with other parameters. If I am runing one after another I'm not getting this error. I think I found somethin similar at:

https://github.com/Azure/Azure-Functions/issues/1123

**Comment by balag0** [comment] 2019-12-09 20:38
I haven't had a chance to try the repro yet. Thanks for investigating this more. Could you explain the scenario little more.
How many threads , what are the individual threads doing (io / cpu etc), how are the results from all the threads collated?

**Comment by wallystart** [comment] 2020-01-08 17:05
Hi! I have the same problem and too, usually it works and sometimes not works . I call to Azure Function from Data Factory v2 and i get this error:

{
    "errorCode": "3608",
    "message": "Call to provided Azure function '' failed with status-'BadGateway' and message - '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>\r\n<style type=\"text/css\">\r\n\r\n</style>\r\n</head>\r\n<body>\r\n<div id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div class=\"content-container\"><fieldset>\r\n  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>\r\n  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n'.",
    "failureType": "UserError",
    "target": "Envio Mail Succes",
    "details": []
}

The app only send mail, its takes 1 second.

region: East US 2
Could it be the free plan?

**Comment by freeone3000** [comment] 2020-05-27 16:25
I'm also getting this issue. I should be getting back a 202 Accepted but instead I'm getting back a failure condition.

**Comment by balag0** [comment] 2020-05-27 17:22
@freeone3000 Could you open a new issue since this is already closed. Feel free to tag me on the new issue and I will take a look. Thanks
Also we will need more details like app name or region and timestamps. What is the operation being tried and what is the return status.

**Comment by GuillaumeLab** [comment] 2020-10-06 20:03
what is the new issue ? i have the same problem

**Comment by RachidAZ** [comment] 2023-03-03 11:50
restarting the function app fixed the issue for me.
