### ISSUE TITLE
Missing Table storage examples

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#448] opened 2019-06-01 19:56 UTC
Here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table

Dependent on generic binding support.

**Comment by jtlz2** [comment] 2019-06-25 18:57
Is this functional but undocumented, or non-functional? If the former, are there samples anywhere? Thanks!

**Comment by twentytwokhz** [comment] 2019-07-01 07:56
Hello! Please add some samples, the documentation is very thin on the Python side.
I wasn't able to find anything useful regarding Table bindings on v2 Azure Functions for Python

**Comment by maiqbal11** [comment] 2019-07-01 20:50
@jtlz2, @twentytwokhz, I'll be working on building a canonical example for this use case. Will update here with details.

**Comment by maiqbal11** [comment] 2019-07-02 21:54
Please refer to the examples here for input and output table bindings: https://github.com/Azure/azure-functions-python-worker/tree/dev/tests/table_functions. Both are http triggered, but you should be able to modify the code to use whatever trigger you need. Closing the issue for now. Feel free to circle back with any questions.

**Comment by maiqbal11** [comment] 2019-07-02 21:56
Didn't realize this was a docs item as well. cc @asavaritayal for any docs additions. 

@twentytwokhz, @jtlz2, also worth noting that the changes needed to enable this will be going out with the next release in ~ 1 week.

**Comment by twentytwokhz** [comment] 2019-07-02 21:58
Awesome! Thank you @maiqbal11 ⭐️

**Comment by twentytwokhz** [comment] 2019-07-08 15:39
@maiqbal11 When is the new release for azure functions python?

**Comment by maiqbal11** [comment] 2019-07-09 15:11
> @maiqbal11 When is the new release for azure functions python?

We are hoping to have it some time next week. There are delays as of now since we are on-boarding a new team to perform validation for our production bits.

**Comment by twentytwokhz** [comment] 2019-07-11 10:24
@maiqbal11 I tried the samples provided for the table input binding with the latest released 1.0.0b9 azure functions worker. I'm running the python function locally within a venv that is setup correctly.
When trying to invoke the HTTP Trigger function I get the following error:

> System.Private.CoreLib: Exception while executing function: Functions.ProcessData_HttpTrigger. System.Private.CoreLib: Result: Failure
Exception: FunctionLoadError: cannot load the ProcessData_HttpTrigger function: unknown type for testEntity binding: "table"
Stack:   File "C:\Users\florin.bobis\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure\functions_worker\dispatcher.py", line 233, in _handle__function_load_request    
    function_id, func, func_request.metadata)
  File "C:\Users\florin.bobis\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure\functions_worker\functions.py", line 179, in add_function
    f'unknown type for {param.name} binding: "{desc.type}"')

How can I fix this?
Thank you in advance :)

**Comment by maiqbal11** [comment] 2019-07-11 15:05
@twentytwokhz, could you elaborate more on how you are using the latest worker? We haven't yet released the core tools corresponding to this worker release so would be helpful to understand how you are going about enabling it.

**Comment by twentytwokhz** [comment] 2019-07-12 16:55
@maiqbal11  I supposed I just needed to add the reference in the requirements.txt file and it would work..
Guess I was wrong...sowhen can we expect an updated version for the corresponding core tools?
where should I check?

**Comment by maiqbal11** [comment] 2019-07-12 17:40
@alrod, I believe the core tools should be released very soon? Looks like the host runtime release was completed a few days ago: https://github.com/Azure/app-service-announcements/issues/182. We also have pending release for the Docker image that is used for the Python which should go out early next week. So, overall, I would say mid next week.

**Comment by anirudhgarg** [comment] 2019-11-05 23:59
@kulkarnisonia16  assigned this to you to add the links to the documentation for table storage in our official docs. They are here: https://github.com/Azure/azure-functions-python-worker/tree/dev/tests/endtoend/table_functions/table_out_binding and https://github.com/Azure/azure-functions-python-worker/tree/dev/tests/endtoend/table_functions/table_in_binding

**Comment by stefanushinardi** [comment] 2021-02-01 16:59
Closing as the issue is resolved. ref: [output](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table-output?tabs=python) and [input](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table-input?tabs=python)

**Closed by stefanushinardi** 2021-02-01 16:59 UTC
Labels: P0, docs, func-stack: Python
