### ISSUE TITLE
Failed to start language worker process for: python

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#291] opened 2019-01-23 01:28 UTC
Deploying a python function with the following requirements.txt

azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.12.0
PyYAML~=3.13
azure-cli-core==2.0.54
azureml-sdk==1.0.8
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
requests==2.20.1

The portal says this 
<img width="376" alt="screen shot 2019-01-22 at 5 22 38 pm" src="https://user-images.githubusercontent.com/10415876/51576405-ea6eb000-1e6a-11e9-8f03-72aeb75fdf9b.png">

If you use a function without --build-native-deps that doesn't use a docker, it deploys fine. 

Region used: **EastUS** for Linux consumption, storage (we know WestUS has some outage issues)

cc: @michhar 

Use a simple HTTP Trigger with these requirements.txt and you will see the error in the portal

App Name:  **tinysamplesapp**

**Comment by asavaritayal** [comment] 2019-01-23 21:12
@ankitkumarr could you please investigate this?

**Comment by ankitkumarr** [comment] 2019-01-24 00:14
Looks like adding `azureml-sdk==1.0.8` causes the failure. I am not sure why. I will look more into it. I don't think it's related to packaging.

\cc @elprans

**Comment by priyaananthasankar** [comment] 2019-01-24 00:20
@ankitkumarr : Tested it locally with azureml-sdk==1.0.8 and it worked fine. We did --build-native-deps as well because this pulls in PyYAML

**Comment by ankitkumarr** [comment] 2019-01-24 03:02
@priyaananthasankar, is this something that used to work before and broke recently, or is this a new app?

While debugging, this is the error I saw-
```
  File "./worker.py", line 36, in <module>
    main()
  File "./worker.py", line 24, in main
    import azure.functions_worker
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/azure/functions_worker/__init__.py", line 1, in <module>
    from . import aio_compat
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/azure/functions_worker/aio_compat.py", line 8, in <module>
    import asyncio
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/home/site/wwwroot/worker_venv/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/site/wwwroot/worker_venv/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

@elprans, I suspect this is because one of the dependencies in the `requirements.txt` is bringing in an older version of `concurrent.futures`, and their `concurrent.futures` gets imported when our worker tries to import `futures`. If this is the case, do you know the best mitigation/suggestion for people with such scenarios? The sad part is that this is being brought in by sub-dependencies of `azureml-sdk`.

Should we manually add `root/.pyenv/versions/3.6.6/lib/python3.6/` to the beginning of the `PYTHONPATH` in order for the python's system dependencies to take precedence.

**Comment by priyaananthasankar** [comment] 2019-01-24 18:46
@ankitkumarr Interesting. This is a new app being tested. I think this is the first time we are trying to use aml sdk for python services through functions. We are trying to get python functions to trigger an aml job, So in case of C#, if the host uses NewtonSoft version 9 and if the code uses version 11 as a sub dependency, then today we can specify version 11 as a main dependency in the code and the host will still run at version 9. Does this isolation exist in Python? Also what version of concurrent.futures does the worker use? We could try explicitly adding it in requirements.txt. 
cc: @michhar

**Comment by ankitkumarr** [comment] 2019-01-24 20:13
@priyaananthasankar, I think this was problem caused by user's dependencies taking precedence over the dependencies in our docker container. 

This should be fixed by https://github.com/Azure/azure-functions-docker/pull/66.
It will be available in our docker containers by next week I believe.

Let us know if you continue seeing issues.

**Closed** 2019-01-28 16:53 UTC
